//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace ComputeAndroidApp.WorkOrderWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IWorkOrderSvc", Namespace="http://tempuri.org/")]
    public partial class WorkOrderSvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgeWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitWorkOrderResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkWorkOrderInComputationOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgeCommunicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOutstandingCommunicationsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WorkOrderSvc() {
            this.Url = "http://192.168.1.65/WebService/WorkOrderSvc.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateWorkOrderCompletedEventHandler CreateWorkOrderCompleted;
        
        /// <remarks/>
        public event CancelWorkOrderCompletedEventHandler CancelWorkOrderCompleted;
        
        /// <remarks/>
        public event GetWorkOrderCompletedEventHandler GetWorkOrderCompleted;
        
        /// <remarks/>
        public event AcknowledgeWorkOrderCompletedEventHandler AcknowledgeWorkOrderCompleted;
        
        /// <remarks/>
        public event SubmitWorkOrderResultCompletedEventHandler SubmitWorkOrderResultCompleted;
        
        /// <remarks/>
        public event MarkWorkOrderInComputationCompletedEventHandler MarkWorkOrderInComputationCompleted;
        
        /// <remarks/>
        public event AcknowledgeCommunicationCompletedEventHandler AcknowledgeCommunicationCompleted;
        
        /// <remarks/>
        public event GetOutstandingCommunicationsCompletedEventHandler GetOutstandingCommunicationsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/CreateWorkOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WorkOrder CreateWorkOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified, int applicationId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool applicationIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string paramList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string backgroundProcessFunction, int localDeviceWORef, [System.Xml.Serialization.XmlIgnoreAttribute()] bool localDeviceWORefSpecified) {
            object[] results = this.Invoke("CreateWorkOrder", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified,
                        applicationId,
                        applicationIdSpecified,
                        paramList,
                        backgroundProcessFunction,
                        localDeviceWORef,
                        localDeviceWORefSpecified});
            return ((WorkOrder)(results[0]));
        }
        
        /// <remarks/>
        public void CreateWorkOrderAsync(string at, int deviceId, bool deviceIdSpecified, int applicationId, bool applicationIdSpecified, string paramList, string backgroundProcessFunction, int localDeviceWORef, bool localDeviceWORefSpecified) {
            this.CreateWorkOrderAsync(at, deviceId, deviceIdSpecified, applicationId, applicationIdSpecified, paramList, backgroundProcessFunction, localDeviceWORef, localDeviceWORefSpecified, null);
        }
        
        /// <remarks/>
        public void CreateWorkOrderAsync(string at, int deviceId, bool deviceIdSpecified, int applicationId, bool applicationIdSpecified, string paramList, string backgroundProcessFunction, int localDeviceWORef, bool localDeviceWORefSpecified, object userState) {
            if ((this.CreateWorkOrderOperationCompleted == null)) {
                this.CreateWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWorkOrderOperationCompleted);
            }
            this.InvokeAsync("CreateWorkOrder", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified,
                        applicationId,
                        applicationIdSpecified,
                        paramList,
                        backgroundProcessFunction,
                        localDeviceWORef,
                        localDeviceWORefSpecified}, this.CreateWorkOrderOperationCompleted, userState);
        }
        
        private void OnCreateWorkOrderOperationCompleted(object arg) {
            if ((this.CreateWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWorkOrderCompleted(this, new CreateWorkOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/CancelWorkOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelWorkOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] int[] localDeviceIdList) {
            this.Invoke("CancelWorkOrder", new object[] {
                        at,
                        localDeviceIdList});
        }
        
        /// <remarks/>
        public void CancelWorkOrderAsync(string at, int[] localDeviceIdList) {
            this.CancelWorkOrderAsync(at, localDeviceIdList, null);
        }
        
        /// <remarks/>
        public void CancelWorkOrderAsync(string at, int[] localDeviceIdList, object userState) {
            if ((this.CancelWorkOrderOperationCompleted == null)) {
                this.CancelWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelWorkOrderOperationCompleted);
            }
            this.InvokeAsync("CancelWorkOrder", new object[] {
                        at,
                        localDeviceIdList}, this.CancelWorkOrderOperationCompleted, userState);
        }
        
        private void OnCancelWorkOrderOperationCompleted(object arg) {
            if ((this.CancelWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelWorkOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/GetWorkOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WorkOrderTrimmed GetWorkOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified, int workOrderId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool workOrderIdSpecified) {
            object[] results = this.Invoke("GetWorkOrder", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified,
                        workOrderId,
                        workOrderIdSpecified});
            return ((WorkOrderTrimmed)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkOrderAsync(string at, int deviceId, bool deviceIdSpecified, int workOrderId, bool workOrderIdSpecified) {
            this.GetWorkOrderAsync(at, deviceId, deviceIdSpecified, workOrderId, workOrderIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetWorkOrderAsync(string at, int deviceId, bool deviceIdSpecified, int workOrderId, bool workOrderIdSpecified, object userState) {
            if ((this.GetWorkOrderOperationCompleted == null)) {
                this.GetWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkOrderOperationCompleted);
            }
            this.InvokeAsync("GetWorkOrder", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified,
                        workOrderId,
                        workOrderIdSpecified}, this.GetWorkOrderOperationCompleted, userState);
        }
        
        private void OnGetWorkOrderOperationCompleted(object arg) {
            if ((this.GetWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkOrderCompleted(this, new GetWorkOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/AcknowledgeWorkOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AcknowledgeWorkOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int workOrderId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool workOrderIdSpecified) {
            this.Invoke("AcknowledgeWorkOrder", new object[] {
                        at,
                        workOrderId,
                        workOrderIdSpecified});
        }
        
        /// <remarks/>
        public void AcknowledgeWorkOrderAsync(string at, int workOrderId, bool workOrderIdSpecified) {
            this.AcknowledgeWorkOrderAsync(at, workOrderId, workOrderIdSpecified, null);
        }
        
        /// <remarks/>
        public void AcknowledgeWorkOrderAsync(string at, int workOrderId, bool workOrderIdSpecified, object userState) {
            if ((this.AcknowledgeWorkOrderOperationCompleted == null)) {
                this.AcknowledgeWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgeWorkOrderOperationCompleted);
            }
            this.InvokeAsync("AcknowledgeWorkOrder", new object[] {
                        at,
                        workOrderId,
                        workOrderIdSpecified}, this.AcknowledgeWorkOrderOperationCompleted, userState);
        }
        
        private void OnAcknowledgeWorkOrderOperationCompleted(object arg) {
            if ((this.AcknowledgeWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgeWorkOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/SubmitWorkOrderResult", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SubmitWorkOrderResult([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int workOrderId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool workOrderIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string resultJson, System.DateTime compuatationStartTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool compuatationStartTimeSpecified, System.DateTime computationEndTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool computationEndTimeSpecified) {
            this.Invoke("SubmitWorkOrderResult", new object[] {
                        at,
                        workOrderId,
                        workOrderIdSpecified,
                        resultJson,
                        compuatationStartTime,
                        compuatationStartTimeSpecified,
                        computationEndTime,
                        computationEndTimeSpecified});
        }
        
        /// <remarks/>
        public void SubmitWorkOrderResultAsync(string at, int workOrderId, bool workOrderIdSpecified, string resultJson, System.DateTime compuatationStartTime, bool compuatationStartTimeSpecified, System.DateTime computationEndTime, bool computationEndTimeSpecified) {
            this.SubmitWorkOrderResultAsync(at, workOrderId, workOrderIdSpecified, resultJson, compuatationStartTime, compuatationStartTimeSpecified, computationEndTime, computationEndTimeSpecified, null);
        }
        
        /// <remarks/>
        public void SubmitWorkOrderResultAsync(string at, int workOrderId, bool workOrderIdSpecified, string resultJson, System.DateTime compuatationStartTime, bool compuatationStartTimeSpecified, System.DateTime computationEndTime, bool computationEndTimeSpecified, object userState) {
            if ((this.SubmitWorkOrderResultOperationCompleted == null)) {
                this.SubmitWorkOrderResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitWorkOrderResultOperationCompleted);
            }
            this.InvokeAsync("SubmitWorkOrderResult", new object[] {
                        at,
                        workOrderId,
                        workOrderIdSpecified,
                        resultJson,
                        compuatationStartTime,
                        compuatationStartTimeSpecified,
                        computationEndTime,
                        computationEndTimeSpecified}, this.SubmitWorkOrderResultOperationCompleted, userState);
        }
        
        private void OnSubmitWorkOrderResultOperationCompleted(object arg) {
            if ((this.SubmitWorkOrderResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitWorkOrderResultCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/MarkWorkOrderInComputation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MarkWorkOrderInComputation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int workOrderId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool workOrderIdSpecified) {
            this.Invoke("MarkWorkOrderInComputation", new object[] {
                        at,
                        workOrderId,
                        workOrderIdSpecified});
        }
        
        /// <remarks/>
        public void MarkWorkOrderInComputationAsync(string at, int workOrderId, bool workOrderIdSpecified) {
            this.MarkWorkOrderInComputationAsync(at, workOrderId, workOrderIdSpecified, null);
        }
        
        /// <remarks/>
        public void MarkWorkOrderInComputationAsync(string at, int workOrderId, bool workOrderIdSpecified, object userState) {
            if ((this.MarkWorkOrderInComputationOperationCompleted == null)) {
                this.MarkWorkOrderInComputationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkWorkOrderInComputationOperationCompleted);
            }
            this.InvokeAsync("MarkWorkOrderInComputation", new object[] {
                        at,
                        workOrderId,
                        workOrderIdSpecified}, this.MarkWorkOrderInComputationOperationCompleted, userState);
        }
        
        private void OnMarkWorkOrderInComputationOperationCompleted(object arg) {
            if ((this.MarkWorkOrderInComputationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkWorkOrderInComputationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/AcknowledgeCommunication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AcknowledgeCommunication([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int communicationId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool communicationIdSpecified, System.DateTime recieveTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recieveTimeSpecified) {
            this.Invoke("AcknowledgeCommunication", new object[] {
                        at,
                        communicationId,
                        communicationIdSpecified,
                        recieveTime,
                        recieveTimeSpecified});
        }
        
        /// <remarks/>
        public void AcknowledgeCommunicationAsync(string at, int communicationId, bool communicationIdSpecified, System.DateTime recieveTime, bool recieveTimeSpecified) {
            this.AcknowledgeCommunicationAsync(at, communicationId, communicationIdSpecified, recieveTime, recieveTimeSpecified, null);
        }
        
        /// <remarks/>
        public void AcknowledgeCommunicationAsync(string at, int communicationId, bool communicationIdSpecified, System.DateTime recieveTime, bool recieveTimeSpecified, object userState) {
            if ((this.AcknowledgeCommunicationOperationCompleted == null)) {
                this.AcknowledgeCommunicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgeCommunicationOperationCompleted);
            }
            this.InvokeAsync("AcknowledgeCommunication", new object[] {
                        at,
                        communicationId,
                        communicationIdSpecified,
                        recieveTime,
                        recieveTimeSpecified}, this.AcknowledgeCommunicationOperationCompleted, userState);
        }
        
        private void OnAcknowledgeCommunicationOperationCompleted(object arg) {
            if ((this.AcknowledgeCommunicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgeCommunicationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IWorkOrderSvc/GetOutstandingCommunications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
        public CommunicationPackage[] GetOutstandingCommunications([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified) {
            object[] results = this.Invoke("GetOutstandingCommunications", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified});
            return ((CommunicationPackage[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOutstandingCommunicationsAsync(string at, int deviceId, bool deviceIdSpecified) {
            this.GetOutstandingCommunicationsAsync(at, deviceId, deviceIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetOutstandingCommunicationsAsync(string at, int deviceId, bool deviceIdSpecified, object userState) {
            if ((this.GetOutstandingCommunicationsOperationCompleted == null)) {
                this.GetOutstandingCommunicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOutstandingCommunicationsOperationCompleted);
            }
            this.InvokeAsync("GetOutstandingCommunications", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified}, this.GetOutstandingCommunicationsOperationCompleted, userState);
        }
        
        private void OnGetOutstandingCommunicationsOperationCompleted(object arg) {
            if ((this.GetOutstandingCommunicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOutstandingCommunicationsCompleted(this, new GetOutstandingCommunicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class WorkOrder {
        
        private int applicationIdk__BackingFieldField;
        
        private string commPackageJsonk__BackingFieldField;
        
        private CommunicationPackage[] communicationPackagesk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> endComputationTimek__BackingFieldField;
        
        private int localDeviceIdk__BackingFieldField;
        
        private System.DateTime receiveTimek__BackingFieldField;
        
        private System.Nullable<System.DateTime> slaveWorkOrderLastCommunicationk__BackingFieldField;
        
        private System.Nullable<int> slaveWorkerIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> slaveWorkerSubmitk__BackingFieldField;
        
        private System.Nullable<System.DateTime> startComputationTimek__BackingFieldField;
        
        private UserDevice userDevice1k__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        private WorkApplication workApplicationk__BackingFieldField;
        
        private int workOrderIdk__BackingFieldField;
        
        private string workOrderResultJsonk__BackingFieldField;
        
        private string workOrderStatusk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationId>k__BackingField")]
        public int ApplicationIdk__BackingField {
            get {
                return this.applicationIdk__BackingFieldField;
            }
            set {
                this.applicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CommPackageJson>k__BackingField", IsNullable=true)]
        public string CommPackageJsonk__BackingField {
            get {
                return this.commPackageJsonk__BackingFieldField;
            }
            set {
                this.commPackageJsonk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<CommunicationPackages>k__BackingField", IsNullable=true)]
        public CommunicationPackage[] CommunicationPackagesk__BackingField {
            get {
                return this.communicationPackagesk__BackingFieldField;
            }
            set {
                this.communicationPackagesk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<EndComputationTime>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> EndComputationTimek__BackingField {
            get {
                return this.endComputationTimek__BackingFieldField;
            }
            set {
                this.endComputationTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LocalDeviceId>k__BackingField")]
        public int LocalDeviceIdk__BackingField {
            get {
                return this.localDeviceIdk__BackingFieldField;
            }
            set {
                this.localDeviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ReceiveTime>k__BackingField")]
        public System.DateTime ReceiveTimek__BackingField {
            get {
                return this.receiveTimek__BackingFieldField;
            }
            set {
                this.receiveTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkOrderLastCommunication>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> SlaveWorkOrderLastCommunicationk__BackingField {
            get {
                return this.slaveWorkOrderLastCommunicationk__BackingFieldField;
            }
            set {
                this.slaveWorkOrderLastCommunicationk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkerId>k__BackingField", IsNullable=true)]
        public System.Nullable<int> SlaveWorkerIdk__BackingField {
            get {
                return this.slaveWorkerIdk__BackingFieldField;
            }
            set {
                this.slaveWorkerIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkerSubmit>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> SlaveWorkerSubmitk__BackingField {
            get {
                return this.slaveWorkerSubmitk__BackingFieldField;
            }
            set {
                this.slaveWorkerSubmitk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StartComputationTime>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> StartComputationTimek__BackingField {
            get {
                return this.startComputationTimek__BackingFieldField;
            }
            set {
                this.startComputationTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice1>k__BackingField", IsNullable=true)]
        public UserDevice UserDevice1k__BackingField {
            get {
                return this.userDevice1k__BackingFieldField;
            }
            set {
                this.userDevice1k__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkApplication>k__BackingField", IsNullable=true)]
        public WorkApplication WorkApplicationk__BackingField {
            get {
                return this.workApplicationk__BackingFieldField;
            }
            set {
                this.workApplicationk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderId>k__BackingField")]
        public int WorkOrderIdk__BackingField {
            get {
                return this.workOrderIdk__BackingFieldField;
            }
            set {
                this.workOrderIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderResultJson>k__BackingField", IsNullable=true)]
        public string WorkOrderResultJsonk__BackingField {
            get {
                return this.workOrderResultJsonk__BackingFieldField;
            }
            set {
                this.workOrderResultJsonk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderStatus>k__BackingField", IsNullable=true)]
        public string WorkOrderStatusk__BackingField {
            get {
                return this.workOrderStatusk__BackingFieldField;
            }
            set {
                this.workOrderStatusk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class CommunicationPackage {
        
        private int communicationIdk__BackingFieldField;
        
        private int communicationTypek__BackingFieldField;
        
        private System.Nullable<System.DateTime> dateAcknowledgedk__BackingFieldField;
        
        private string responsek__BackingFieldField;
        
        private int sendAttemptsk__BackingFieldField;
        
        private string statusk__BackingFieldField;
        
        private System.DateTime submitDatek__BackingFieldField;
        
        private int targetDeviceIdk__BackingFieldField;
        
        private System.Nullable<int> workOrderIdk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CommunicationId>k__BackingField")]
        public int CommunicationIdk__BackingField {
            get {
                return this.communicationIdk__BackingFieldField;
            }
            set {
                this.communicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CommunicationType>k__BackingField")]
        public int CommunicationTypek__BackingField {
            get {
                return this.communicationTypek__BackingFieldField;
            }
            set {
                this.communicationTypek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DateAcknowledged>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> DateAcknowledgedk__BackingField {
            get {
                return this.dateAcknowledgedk__BackingFieldField;
            }
            set {
                this.dateAcknowledgedk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Response>k__BackingField", IsNullable=true)]
        public string Responsek__BackingField {
            get {
                return this.responsek__BackingFieldField;
            }
            set {
                this.responsek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SendAttempts>k__BackingField")]
        public int SendAttemptsk__BackingField {
            get {
                return this.sendAttemptsk__BackingFieldField;
            }
            set {
                this.sendAttemptsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Status>k__BackingField", IsNullable=true)]
        public string Statusk__BackingField {
            get {
                return this.statusk__BackingFieldField;
            }
            set {
                this.statusk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubmitDate>k__BackingField")]
        public System.DateTime SubmitDatek__BackingField {
            get {
                return this.submitDatek__BackingFieldField;
            }
            set {
                this.submitDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<TargetDeviceId>k__BackingField")]
        public int TargetDeviceIdk__BackingField {
            get {
                return this.targetDeviceIdk__BackingFieldField;
            }
            set {
                this.targetDeviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderId>k__BackingField", IsNullable=true)]
        public System.Nullable<int> WorkOrderIdk__BackingField {
            get {
                return this.workOrderIdk__BackingFieldField;
            }
            set {
                this.workOrderIdk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    public partial class WorkOrderTrimmed {
        
        private int applicationIdk__BackingFieldField;
        
        private string applicationUIResultIntentk__BackingFieldField;
        
        private string commPackageJsonk__BackingFieldField;
        
        private string computeAppIntentk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private int deviceLocalRequestIdk__BackingFieldField;
        
        private string deviceUIRefk__BackingFieldField;
        
        private System.DateTime receiveTimek__BackingFieldField;
        
        private System.Nullable<System.DateTime> slaveWorkOrderLastCommunicationk__BackingFieldField;
        
        private System.Nullable<int> slaveWorkerIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> slaveWorkerSubmitk__BackingFieldField;
        
        private int workOrderIdk__BackingFieldField;
        
        private string workOrderResultJsonk__BackingFieldField;
        
        private string workOrderStatusk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationId>k__BackingField")]
        public int ApplicationIdk__BackingField {
            get {
                return this.applicationIdk__BackingFieldField;
            }
            set {
                this.applicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationUIResultIntent>k__BackingField", IsNullable=true)]
        public string ApplicationUIResultIntentk__BackingField {
            get {
                return this.applicationUIResultIntentk__BackingFieldField;
            }
            set {
                this.applicationUIResultIntentk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CommPackageJson>k__BackingField", IsNullable=true)]
        public string CommPackageJsonk__BackingField {
            get {
                return this.commPackageJsonk__BackingFieldField;
            }
            set {
                this.commPackageJsonk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ComputeAppIntent>k__BackingField", IsNullable=true)]
        public string ComputeAppIntentk__BackingField {
            get {
                return this.computeAppIntentk__BackingFieldField;
            }
            set {
                this.computeAppIntentk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceLocalRequestId>k__BackingField")]
        public int DeviceLocalRequestIdk__BackingField {
            get {
                return this.deviceLocalRequestIdk__BackingFieldField;
            }
            set {
                this.deviceLocalRequestIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceUIRef>k__BackingField", IsNullable=true)]
        public string DeviceUIRefk__BackingField {
            get {
                return this.deviceUIRefk__BackingFieldField;
            }
            set {
                this.deviceUIRefk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ReceiveTime>k__BackingField")]
        public System.DateTime ReceiveTimek__BackingField {
            get {
                return this.receiveTimek__BackingFieldField;
            }
            set {
                this.receiveTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkOrderLastCommunication>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> SlaveWorkOrderLastCommunicationk__BackingField {
            get {
                return this.slaveWorkOrderLastCommunicationk__BackingFieldField;
            }
            set {
                this.slaveWorkOrderLastCommunicationk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkerId>k__BackingField", IsNullable=true)]
        public System.Nullable<int> SlaveWorkerIdk__BackingField {
            get {
                return this.slaveWorkerIdk__BackingFieldField;
            }
            set {
                this.slaveWorkerIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkerSubmit>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> SlaveWorkerSubmitk__BackingField {
            get {
                return this.slaveWorkerSubmitk__BackingFieldField;
            }
            set {
                this.slaveWorkerSubmitk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderId>k__BackingField")]
        public int WorkOrderIdk__BackingField {
            get {
                return this.workOrderIdk__BackingFieldField;
            }
            set {
                this.workOrderIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderResultJson>k__BackingField", IsNullable=true)]
        public string WorkOrderResultJsonk__BackingField {
            get {
                return this.workOrderResultJsonk__BackingFieldField;
            }
            set {
                this.workOrderResultJsonk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderStatus>k__BackingField", IsNullable=true)]
        public string WorkOrderStatusk__BackingField {
            get {
                return this.workOrderStatusk__BackingFieldField;
            }
            set {
                this.workOrderStatusk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class WorkApplication {
        
        private string applicationCreatork__BackingFieldField;
        
        private string applicationDescriptionk__BackingFieldField;
        
        private int applicationIdk__BackingFieldField;
        
        private string applicationNamek__BackingFieldField;
        
        private string applicationNamespacek__BackingFieldField;
        
        private string applicationPackageURLk__BackingFieldField;
        
        private string applicationUIResultIntentk__BackingFieldField;
        
        private int applicationVersionk__BackingFieldField;
        
        private string applicationWorkIntentk__BackingFieldField;
        
        private DeviceAppInstallation[] deviceAppInstallationsk__BackingFieldField;
        
        private WorkOrder[] workOrdersk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationCreator>k__BackingField", IsNullable=true)]
        public string ApplicationCreatork__BackingField {
            get {
                return this.applicationCreatork__BackingFieldField;
            }
            set {
                this.applicationCreatork__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationDescription>k__BackingField", IsNullable=true)]
        public string ApplicationDescriptionk__BackingField {
            get {
                return this.applicationDescriptionk__BackingFieldField;
            }
            set {
                this.applicationDescriptionk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationId>k__BackingField")]
        public int ApplicationIdk__BackingField {
            get {
                return this.applicationIdk__BackingFieldField;
            }
            set {
                this.applicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationName>k__BackingField", IsNullable=true)]
        public string ApplicationNamek__BackingField {
            get {
                return this.applicationNamek__BackingFieldField;
            }
            set {
                this.applicationNamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationNamespace>k__BackingField", IsNullable=true)]
        public string ApplicationNamespacek__BackingField {
            get {
                return this.applicationNamespacek__BackingFieldField;
            }
            set {
                this.applicationNamespacek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationPackageURL>k__BackingField", IsNullable=true)]
        public string ApplicationPackageURLk__BackingField {
            get {
                return this.applicationPackageURLk__BackingFieldField;
            }
            set {
                this.applicationPackageURLk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationUIResultIntent>k__BackingField", IsNullable=true)]
        public string ApplicationUIResultIntentk__BackingField {
            get {
                return this.applicationUIResultIntentk__BackingFieldField;
            }
            set {
                this.applicationUIResultIntentk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationVersion>k__BackingField")]
        public int ApplicationVersionk__BackingField {
            get {
                return this.applicationVersionk__BackingFieldField;
            }
            set {
                this.applicationVersionk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationWorkIntent>k__BackingField", IsNullable=true)]
        public string ApplicationWorkIntentk__BackingField {
            get {
                return this.applicationWorkIntentk__BackingFieldField;
            }
            set {
                this.applicationWorkIntentk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<DeviceAppInstallations>k__BackingField", IsNullable=true)]
        public DeviceAppInstallation[] DeviceAppInstallationsk__BackingField {
            get {
                return this.deviceAppInstallationsk__BackingFieldField;
            }
            set {
                this.deviceAppInstallationsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<WorkOrders>k__BackingField", IsNullable=true)]
        public WorkOrder[] WorkOrdersk__BackingField {
            get {
                return this.workOrdersk__BackingFieldField;
            }
            set {
                this.workOrdersk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class DeviceAppInstallation {
        
        private int applicationDevicePairIdk__BackingFieldField;
        
        private int applicationIdk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private System.DateTime installDatek__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        private WorkApplication workApplicationk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationDevicePairId>k__BackingField")]
        public int ApplicationDevicePairIdk__BackingField {
            get {
                return this.applicationDevicePairIdk__BackingFieldField;
            }
            set {
                this.applicationDevicePairIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationId>k__BackingField")]
        public int ApplicationIdk__BackingField {
            get {
                return this.applicationIdk__BackingFieldField;
            }
            set {
                this.applicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<InstallDate>k__BackingField")]
        public System.DateTime InstallDatek__BackingField {
            get {
                return this.installDatek__BackingFieldField;
            }
            set {
                this.installDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkApplication>k__BackingField", IsNullable=true)]
        public WorkApplication WorkApplicationk__BackingField {
            get {
                return this.workApplicationk__BackingFieldField;
            }
            set {
                this.workApplicationk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class UserDevice {
        
        private ActiveDevice activeDevicek__BackingFieldField;
        
        private AuthenticationToken authenticationTokenk__BackingFieldField;
        
        private CommunicationPackage[] communicationPackagesk__BackingFieldField;
        
        private DeviceAccessRestriction[] deviceAccessRestrictionsk__BackingFieldField;
        
        private DeviceAppInstallation[] deviceAppInstallationsk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private int deviceMemoryResourcek__BackingFieldField;
        
        private int deviceProcRatingk__BackingFieldField;
        
        private string deviceTypek__BackingFieldField;
        
        private string gCMCodek__BackingFieldField;
        
        private User userk__BackingFieldField;
        
        private string usernamek__BackingFieldField;
        
        private WorkOrder[] workOrders1k__BackingFieldField;
        
        private WorkOrder[] workOrdersk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ActiveDevice>k__BackingField", IsNullable=true)]
        public ActiveDevice ActiveDevicek__BackingField {
            get {
                return this.activeDevicek__BackingFieldField;
            }
            set {
                this.activeDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<AuthenticationToken>k__BackingField", IsNullable=true)]
        public AuthenticationToken AuthenticationTokenk__BackingField {
            get {
                return this.authenticationTokenk__BackingFieldField;
            }
            set {
                this.authenticationTokenk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<CommunicationPackages>k__BackingField", IsNullable=true)]
        public CommunicationPackage[] CommunicationPackagesk__BackingField {
            get {
                return this.communicationPackagesk__BackingFieldField;
            }
            set {
                this.communicationPackagesk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<DeviceAccessRestrictions>k__BackingField", IsNullable=true)]
        public DeviceAccessRestriction[] DeviceAccessRestrictionsk__BackingField {
            get {
                return this.deviceAccessRestrictionsk__BackingFieldField;
            }
            set {
                this.deviceAccessRestrictionsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<DeviceAppInstallations>k__BackingField", IsNullable=true)]
        public DeviceAppInstallation[] DeviceAppInstallationsk__BackingField {
            get {
                return this.deviceAppInstallationsk__BackingFieldField;
            }
            set {
                this.deviceAppInstallationsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceMemoryResource>k__BackingField")]
        public int DeviceMemoryResourcek__BackingField {
            get {
                return this.deviceMemoryResourcek__BackingFieldField;
            }
            set {
                this.deviceMemoryResourcek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceProcRating>k__BackingField")]
        public int DeviceProcRatingk__BackingField {
            get {
                return this.deviceProcRatingk__BackingFieldField;
            }
            set {
                this.deviceProcRatingk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceType>k__BackingField", IsNullable=true)]
        public string DeviceTypek__BackingField {
            get {
                return this.deviceTypek__BackingFieldField;
            }
            set {
                this.deviceTypek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<GCMCode>k__BackingField", IsNullable=true)]
        public string GCMCodek__BackingField {
            get {
                return this.gCMCodek__BackingFieldField;
            }
            set {
                this.gCMCodek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<User>k__BackingField", IsNullable=true)]
        public User Userk__BackingField {
            get {
                return this.userk__BackingFieldField;
            }
            set {
                this.userk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Username>k__BackingField", IsNullable=true)]
        public string Usernamek__BackingField {
            get {
                return this.usernamek__BackingFieldField;
            }
            set {
                this.usernamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<WorkOrders1>k__BackingField", IsNullable=true)]
        public WorkOrder[] WorkOrders1k__BackingField {
            get {
                return this.workOrders1k__BackingFieldField;
            }
            set {
                this.workOrders1k__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<WorkOrders>k__BackingField", IsNullable=true)]
        public WorkOrder[] WorkOrdersk__BackingField {
            get {
                return this.workOrdersk__BackingFieldField;
            }
            set {
                this.workOrdersk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class ActiveDevice {
        
        private int deviceIdk__BackingFieldField;
        
        private System.DateTime lastActiveSendk__BackingFieldField;
        
        private System.DateTime lastFetchk__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastActiveSend>k__BackingField")]
        public System.DateTime LastActiveSendk__BackingField {
            get {
                return this.lastActiveSendk__BackingFieldField;
            }
            set {
                this.lastActiveSendk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastFetch>k__BackingField")]
        public System.DateTime LastFetchk__BackingField {
            get {
                return this.lastFetchk__BackingFieldField;
            }
            set {
                this.lastFetchk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class AuthenticationToken {
        
        private System.DateTime creationDatek__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> lastAccessDatek__BackingFieldField;
        
        private string tokenk__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        private User userk__BackingFieldField;
        
        private string usernamek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CreationDate>k__BackingField")]
        public System.DateTime CreationDatek__BackingField {
            get {
                return this.creationDatek__BackingFieldField;
            }
            set {
                this.creationDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastAccessDate>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> LastAccessDatek__BackingField {
            get {
                return this.lastAccessDatek__BackingFieldField;
            }
            set {
                this.lastAccessDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Token>k__BackingField", IsNullable=true)]
        public string Tokenk__BackingField {
            get {
                return this.tokenk__BackingFieldField;
            }
            set {
                this.tokenk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<User>k__BackingField", IsNullable=true)]
        public User Userk__BackingField {
            get {
                return this.userk__BackingFieldField;
            }
            set {
                this.userk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Username>k__BackingField", IsNullable=true)]
        public string Usernamek__BackingField {
            get {
                return this.usernamek__BackingFieldField;
            }
            set {
                this.usernamek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class User {
        
        private AuthenticationToken[] authenticationTokensk__BackingFieldField;
        
        private string forenamek__BackingFieldField;
        
        private string passwordk__BackingFieldField;
        
        private string surnamek__BackingFieldField;
        
        private UserDevice[] userDevicesk__BackingFieldField;
        
        private int userIdk__BackingFieldField;
        
        private string usernamek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<AuthenticationTokens>k__BackingField", IsNullable=true)]
        public AuthenticationToken[] AuthenticationTokensk__BackingField {
            get {
                return this.authenticationTokensk__BackingFieldField;
            }
            set {
                this.authenticationTokensk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Forename>k__BackingField", IsNullable=true)]
        public string Forenamek__BackingField {
            get {
                return this.forenamek__BackingFieldField;
            }
            set {
                this.forenamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Password>k__BackingField", IsNullable=true)]
        public string Passwordk__BackingField {
            get {
                return this.passwordk__BackingFieldField;
            }
            set {
                this.passwordk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Surname>k__BackingField", IsNullable=true)]
        public string Surnamek__BackingField {
            get {
                return this.surnamek__BackingFieldField;
            }
            set {
                this.surnamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<UserDevices>k__BackingField", IsNullable=true)]
        public UserDevice[] UserDevicesk__BackingField {
            get {
                return this.userDevicesk__BackingFieldField;
            }
            set {
                this.userDevicesk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserId>k__BackingField")]
        public int UserIdk__BackingField {
            get {
                return this.userIdk__BackingFieldField;
            }
            set {
                this.userIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Username>k__BackingField", IsNullable=true)]
        public string Usernamek__BackingField {
            get {
                return this.usernamek__BackingFieldField;
            }
            set {
                this.usernamek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class DeviceAccessRestriction {
        
        private int accessRestrictionIdk__BackingFieldField;
        
        private int dayk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private string endTimek__BackingFieldField;
        
        private string startTimek__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<AccessRestrictionId>k__BackingField")]
        public int AccessRestrictionIdk__BackingField {
            get {
                return this.accessRestrictionIdk__BackingFieldField;
            }
            set {
                this.accessRestrictionIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Day>k__BackingField")]
        public int Dayk__BackingField {
            get {
                return this.dayk__BackingFieldField;
            }
            set {
                this.dayk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<EndTime>k__BackingField", DataType="duration")]
        public string EndTimek__BackingField {
            get {
                return this.endTimek__BackingFieldField;
            }
            set {
                this.endTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StartTime>k__BackingField", DataType="duration")]
        public string StartTimek__BackingField {
            get {
                return this.startTimek__BackingFieldField;
            }
            set {
                this.startTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateWorkOrderCompletedEventHandler(object sender, CreateWorkOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkOrder Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkOrder)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CancelWorkOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetWorkOrderCompletedEventHandler(object sender, GetWorkOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkOrderTrimmed Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkOrderTrimmed)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AcknowledgeWorkOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SubmitWorkOrderResultCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MarkWorkOrderInComputationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AcknowledgeCommunicationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetOutstandingCommunicationsCompletedEventHandler(object sender, GetOutstandingCommunicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOutstandingCommunicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOutstandingCommunicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommunicationPackage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommunicationPackage[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591