//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationPackage
    {
        public int CommunicationId { get; set; }
        public int CommunicationType { get; set; }
        public int WorkOrderId { get; set; }
        public int TargetDeviceId { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<System.DateTime> DateAcknowledged { get; set; }
        public string Response { get; set; }
        public string Status { get; set; }
        public int SendAttempts { get; set; }
    }
}
