//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceAppInstallation
    {
        public int ApplicationDevicePairId { get; set; }
        public int ApplicationId { get; set; }
        public int DeviceId { get; set; }
        public System.DateTime InstallDate { get; set; }
    
        public virtual WorkApplication WorkApplication { get; set; }
        public virtual UserDevice UserDevice { get; set; }
    }
}
