//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public UserDevice()
        {
            this.DeviceAppInstallations = new HashSet<DeviceAppInstallation>();
            this.DeviceAccessRestrictions = new HashSet<DeviceAccessRestriction>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.WorkOrders1 = new HashSet<WorkOrder>();
            this.CommunicationPackages = new HashSet<CommunicationPackage>();
        }
    
        public int DeviceId { get; set; }
        public string Username { get; set; }
        public string DeviceType { get; set; }
        public int DeviceMemoryResource { get; set; }
        public int DeviceProcRating { get; set; }
        public string GCMCode { get; set; }
    
        public virtual ICollection<DeviceAppInstallation> DeviceAppInstallations { get; set; }
        public virtual User User { get; set; }
        public virtual AuthenticationToken AuthenticationToken { get; set; }
        public virtual ICollection<DeviceAccessRestriction> DeviceAccessRestrictions { get; set; }
        public virtual ActiveDevice ActiveDevice { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        public virtual ICollection<WorkOrder> WorkOrders1 { get; set; }
        public virtual ICollection<CommunicationPackage> CommunicationPackages { get; set; }
    }
}
