//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public int DeviceId { get; set; }
        public string Username { get; set; }
        public string DeviceType { get; set; }
        public int DeviceMemoryResource { get; set; }
        public int DeviceProcRating { get; set; }
        public string GCMCode { get; set; }
    
        public virtual User User { get; set; }
    }
}
