//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.Communications = new HashSet<Communication>();
        }
    
        public int WorkOrderId { get; set; }
        public int DeviceId { get; set; }
        public int ApplicationId { get; set; }
        public string CommPackageJson { get; set; }
        public System.DateTime ReceiveTime { get; set; }
        public Nullable<int> SlaveWorkerId { get; set; }
        public Nullable<System.DateTime> SlaveWorkerSubmit { get; set; }
        public Nullable<System.DateTime> SlaveWorkOrderLastCommunication { get; set; }
        public string WorkOrderStatus { get; set; }
        public string WorkOrderResultJson { get; set; }
        public Nullable<System.DateTime> StartComputationTime { get; set; }
        public Nullable<System.DateTime> EndComputationTime { get; set; }
        public string DeviceUIRef { get; set; }
    
        public virtual UserDevice UserDevice { get; set; }
        public virtual UserDevice UserDevice1 { get; set; }
        public virtual WorkApplication WorkApplication { get; set; }
        public virtual ICollection<Communication> Communications { get; set; }
    }
}
