//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.WorkOrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommPackage.ParamListItem", Namespace="http://schemas.datacontract.org/2004/07/SharedClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.WorkOrderTrimmed))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.WorkOrder))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.CommunicationPackage[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.CommunicationPackage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.UserDevice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.ActiveDevice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.AuthenticationToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.AuthenticationToken[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.UserDevice[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.DeviceAccessRestriction[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.DeviceAccessRestriction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.DeviceAppInstallation[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.DeviceAppInstallation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.WorkApplication))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.WorkOrder[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestApp.WorkOrderService.CommPackageParamListItem[]))]
    public partial class CommPackageParamListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ParameterNamek__BackingFieldField;
        
        private object ParameterValuek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ParameterName>k__BackingField", IsRequired=true)]
        public string ParameterNamek__BackingField {
            get {
                return this.ParameterNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterNamek__BackingFieldField, value) != true)) {
                    this.ParameterNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("ParameterNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ParameterValue>k__BackingField", IsRequired=true)]
        public object ParameterValuek__BackingField {
            get {
                return this.ParameterValuek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterValuek__BackingFieldField, value) != true)) {
                    this.ParameterValuek__BackingFieldField = value;
                    this.RaisePropertyChanged("ParameterValuek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkOrderTrimmed", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class WorkOrderTrimmed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ApplicationIdk__BackingFieldField;
        
        private string ApplicationUIResultIntentk__BackingFieldField;
        
        private string CommPackageJsonk__BackingFieldField;
        
        private string ComputeAppIntentk__BackingFieldField;
        
        private int DeviceIdk__BackingFieldField;
        
        private string DeviceUIRefk__BackingFieldField;
        
        private System.DateTime ReceiveTimek__BackingFieldField;
        
        private System.Nullable<System.DateTime> SlaveWorkOrderLastCommunicationk__BackingFieldField;
        
        private System.Nullable<int> SlaveWorkerIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> SlaveWorkerSubmitk__BackingFieldField;
        
        private int WorkOrderIdk__BackingFieldField;
        
        private string WorkOrderResultJsonk__BackingFieldField;
        
        private string WorkOrderStatusk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationId>k__BackingField", IsRequired=true)]
        public int ApplicationIdk__BackingField {
            get {
                return this.ApplicationIdk__BackingFieldField;
            }
            set {
                if ((this.ApplicationIdk__BackingFieldField.Equals(value) != true)) {
                    this.ApplicationIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationUIResultIntent>k__BackingField", IsRequired=true)]
        public string ApplicationUIResultIntentk__BackingField {
            get {
                return this.ApplicationUIResultIntentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationUIResultIntentk__BackingFieldField, value) != true)) {
                    this.ApplicationUIResultIntentk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationUIResultIntentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommPackageJson>k__BackingField", IsRequired=true)]
        public string CommPackageJsonk__BackingField {
            get {
                return this.CommPackageJsonk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CommPackageJsonk__BackingFieldField, value) != true)) {
                    this.CommPackageJsonk__BackingFieldField = value;
                    this.RaisePropertyChanged("CommPackageJsonk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ComputeAppIntent>k__BackingField", IsRequired=true)]
        public string ComputeAppIntentk__BackingField {
            get {
                return this.ComputeAppIntentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ComputeAppIntentk__BackingFieldField, value) != true)) {
                    this.ComputeAppIntentk__BackingFieldField = value;
                    this.RaisePropertyChanged("ComputeAppIntentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceId>k__BackingField", IsRequired=true)]
        public int DeviceIdk__BackingField {
            get {
                return this.DeviceIdk__BackingFieldField;
            }
            set {
                if ((this.DeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceUIRef>k__BackingField", IsRequired=true)]
        public string DeviceUIRefk__BackingField {
            get {
                return this.DeviceUIRefk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceUIRefk__BackingFieldField, value) != true)) {
                    this.DeviceUIRefk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceUIRefk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReceiveTime>k__BackingField", IsRequired=true)]
        public System.DateTime ReceiveTimek__BackingField {
            get {
                return this.ReceiveTimek__BackingFieldField;
            }
            set {
                if ((this.ReceiveTimek__BackingFieldField.Equals(value) != true)) {
                    this.ReceiveTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("ReceiveTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SlaveWorkOrderLastCommunication>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> SlaveWorkOrderLastCommunicationk__BackingField {
            get {
                return this.SlaveWorkOrderLastCommunicationk__BackingFieldField;
            }
            set {
                if ((this.SlaveWorkOrderLastCommunicationk__BackingFieldField.Equals(value) != true)) {
                    this.SlaveWorkOrderLastCommunicationk__BackingFieldField = value;
                    this.RaisePropertyChanged("SlaveWorkOrderLastCommunicationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SlaveWorkerId>k__BackingField", IsRequired=true)]
        public System.Nullable<int> SlaveWorkerIdk__BackingField {
            get {
                return this.SlaveWorkerIdk__BackingFieldField;
            }
            set {
                if ((this.SlaveWorkerIdk__BackingFieldField.Equals(value) != true)) {
                    this.SlaveWorkerIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("SlaveWorkerIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SlaveWorkerSubmit>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> SlaveWorkerSubmitk__BackingField {
            get {
                return this.SlaveWorkerSubmitk__BackingFieldField;
            }
            set {
                if ((this.SlaveWorkerSubmitk__BackingFieldField.Equals(value) != true)) {
                    this.SlaveWorkerSubmitk__BackingFieldField = value;
                    this.RaisePropertyChanged("SlaveWorkerSubmitk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrderId>k__BackingField", IsRequired=true)]
        public int WorkOrderIdk__BackingField {
            get {
                return this.WorkOrderIdk__BackingFieldField;
            }
            set {
                if ((this.WorkOrderIdk__BackingFieldField.Equals(value) != true)) {
                    this.WorkOrderIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrderIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrderResultJson>k__BackingField", IsRequired=true)]
        public string WorkOrderResultJsonk__BackingField {
            get {
                return this.WorkOrderResultJsonk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderResultJsonk__BackingFieldField, value) != true)) {
                    this.WorkOrderResultJsonk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrderResultJsonk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrderStatus>k__BackingField", IsRequired=true)]
        public string WorkOrderStatusk__BackingField {
            get {
                return this.WorkOrderStatusk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderStatusk__BackingFieldField, value) != true)) {
                    this.WorkOrderStatusk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrderStatusk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkOrder", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class WorkOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ApplicationIdk__BackingFieldField;
        
        private string CommPackageJsonk__BackingFieldField;
        
        private TestApp.WorkOrderService.CommunicationPackage[] CommunicationPackagesk__BackingFieldField;
        
        private int DeviceIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> EndComputationTimek__BackingFieldField;
        
        private System.DateTime ReceiveTimek__BackingFieldField;
        
        private System.Nullable<System.DateTime> SlaveWorkOrderLastCommunicationk__BackingFieldField;
        
        private System.Nullable<int> SlaveWorkerIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> SlaveWorkerSubmitk__BackingFieldField;
        
        private System.Nullable<System.DateTime> StartComputationTimek__BackingFieldField;
        
        private TestApp.WorkOrderService.UserDevice UserDevice1k__BackingFieldField;
        
        private TestApp.WorkOrderService.UserDevice UserDevicek__BackingFieldField;
        
        private TestApp.WorkOrderService.WorkApplication WorkApplicationk__BackingFieldField;
        
        private int WorkOrderIdk__BackingFieldField;
        
        private string WorkOrderResultJsonk__BackingFieldField;
        
        private string WorkOrderStatusk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationId>k__BackingField", IsRequired=true)]
        public int ApplicationIdk__BackingField {
            get {
                return this.ApplicationIdk__BackingFieldField;
            }
            set {
                if ((this.ApplicationIdk__BackingFieldField.Equals(value) != true)) {
                    this.ApplicationIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommPackageJson>k__BackingField", IsRequired=true)]
        public string CommPackageJsonk__BackingField {
            get {
                return this.CommPackageJsonk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CommPackageJsonk__BackingFieldField, value) != true)) {
                    this.CommPackageJsonk__BackingFieldField = value;
                    this.RaisePropertyChanged("CommPackageJsonk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommunicationPackages>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.CommunicationPackage[] CommunicationPackagesk__BackingField {
            get {
                return this.CommunicationPackagesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationPackagesk__BackingFieldField, value) != true)) {
                    this.CommunicationPackagesk__BackingFieldField = value;
                    this.RaisePropertyChanged("CommunicationPackagesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceId>k__BackingField", IsRequired=true)]
        public int DeviceIdk__BackingField {
            get {
                return this.DeviceIdk__BackingFieldField;
            }
            set {
                if ((this.DeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EndComputationTime>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> EndComputationTimek__BackingField {
            get {
                return this.EndComputationTimek__BackingFieldField;
            }
            set {
                if ((this.EndComputationTimek__BackingFieldField.Equals(value) != true)) {
                    this.EndComputationTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("EndComputationTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReceiveTime>k__BackingField", IsRequired=true)]
        public System.DateTime ReceiveTimek__BackingField {
            get {
                return this.ReceiveTimek__BackingFieldField;
            }
            set {
                if ((this.ReceiveTimek__BackingFieldField.Equals(value) != true)) {
                    this.ReceiveTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("ReceiveTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SlaveWorkOrderLastCommunication>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> SlaveWorkOrderLastCommunicationk__BackingField {
            get {
                return this.SlaveWorkOrderLastCommunicationk__BackingFieldField;
            }
            set {
                if ((this.SlaveWorkOrderLastCommunicationk__BackingFieldField.Equals(value) != true)) {
                    this.SlaveWorkOrderLastCommunicationk__BackingFieldField = value;
                    this.RaisePropertyChanged("SlaveWorkOrderLastCommunicationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SlaveWorkerId>k__BackingField", IsRequired=true)]
        public System.Nullable<int> SlaveWorkerIdk__BackingField {
            get {
                return this.SlaveWorkerIdk__BackingFieldField;
            }
            set {
                if ((this.SlaveWorkerIdk__BackingFieldField.Equals(value) != true)) {
                    this.SlaveWorkerIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("SlaveWorkerIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SlaveWorkerSubmit>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> SlaveWorkerSubmitk__BackingField {
            get {
                return this.SlaveWorkerSubmitk__BackingFieldField;
            }
            set {
                if ((this.SlaveWorkerSubmitk__BackingFieldField.Equals(value) != true)) {
                    this.SlaveWorkerSubmitk__BackingFieldField = value;
                    this.RaisePropertyChanged("SlaveWorkerSubmitk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StartComputationTime>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> StartComputationTimek__BackingField {
            get {
                return this.StartComputationTimek__BackingFieldField;
            }
            set {
                if ((this.StartComputationTimek__BackingFieldField.Equals(value) != true)) {
                    this.StartComputationTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("StartComputationTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserDevice1>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.UserDevice UserDevice1k__BackingField {
            get {
                return this.UserDevice1k__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDevice1k__BackingFieldField, value) != true)) {
                    this.UserDevice1k__BackingFieldField = value;
                    this.RaisePropertyChanged("UserDevice1k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserDevice>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.UserDevice UserDevicek__BackingField {
            get {
                return this.UserDevicek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDevicek__BackingFieldField, value) != true)) {
                    this.UserDevicek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserDevicek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkApplication>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.WorkApplication WorkApplicationk__BackingField {
            get {
                return this.WorkApplicationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkApplicationk__BackingFieldField, value) != true)) {
                    this.WorkApplicationk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkApplicationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrderId>k__BackingField", IsRequired=true)]
        public int WorkOrderIdk__BackingField {
            get {
                return this.WorkOrderIdk__BackingFieldField;
            }
            set {
                if ((this.WorkOrderIdk__BackingFieldField.Equals(value) != true)) {
                    this.WorkOrderIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrderIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrderResultJson>k__BackingField", IsRequired=true)]
        public string WorkOrderResultJsonk__BackingField {
            get {
                return this.WorkOrderResultJsonk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderResultJsonk__BackingFieldField, value) != true)) {
                    this.WorkOrderResultJsonk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrderResultJsonk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrderStatus>k__BackingField", IsRequired=true)]
        public string WorkOrderStatusk__BackingField {
            get {
                return this.WorkOrderStatusk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrderStatusk__BackingFieldField, value) != true)) {
                    this.WorkOrderStatusk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrderStatusk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommunicationPackage", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class CommunicationPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CommunicationIdk__BackingFieldField;
        
        private int CommunicationTypek__BackingFieldField;
        
        private System.Nullable<System.DateTime> DateAcknowledgedk__BackingFieldField;
        
        private string Responsek__BackingFieldField;
        
        private System.DateTime SubmitDatek__BackingFieldField;
        
        private int TargetDeviceIdk__BackingFieldField;
        
        private int WorkOrderIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommunicationId>k__BackingField", IsRequired=true)]
        public int CommunicationIdk__BackingField {
            get {
                return this.CommunicationIdk__BackingFieldField;
            }
            set {
                if ((this.CommunicationIdk__BackingFieldField.Equals(value) != true)) {
                    this.CommunicationIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("CommunicationIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommunicationType>k__BackingField", IsRequired=true)]
        public int CommunicationTypek__BackingField {
            get {
                return this.CommunicationTypek__BackingFieldField;
            }
            set {
                if ((this.CommunicationTypek__BackingFieldField.Equals(value) != true)) {
                    this.CommunicationTypek__BackingFieldField = value;
                    this.RaisePropertyChanged("CommunicationTypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DateAcknowledged>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> DateAcknowledgedk__BackingField {
            get {
                return this.DateAcknowledgedk__BackingFieldField;
            }
            set {
                if ((this.DateAcknowledgedk__BackingFieldField.Equals(value) != true)) {
                    this.DateAcknowledgedk__BackingFieldField = value;
                    this.RaisePropertyChanged("DateAcknowledgedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Response>k__BackingField", IsRequired=true)]
        public string Responsek__BackingField {
            get {
                return this.Responsek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Responsek__BackingFieldField, value) != true)) {
                    this.Responsek__BackingFieldField = value;
                    this.RaisePropertyChanged("Responsek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SubmitDate>k__BackingField", IsRequired=true)]
        public System.DateTime SubmitDatek__BackingField {
            get {
                return this.SubmitDatek__BackingFieldField;
            }
            set {
                if ((this.SubmitDatek__BackingFieldField.Equals(value) != true)) {
                    this.SubmitDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("SubmitDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TargetDeviceId>k__BackingField", IsRequired=true)]
        public int TargetDeviceIdk__BackingField {
            get {
                return this.TargetDeviceIdk__BackingFieldField;
            }
            set {
                if ((this.TargetDeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.TargetDeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("TargetDeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrderId>k__BackingField", IsRequired=true)]
        public int WorkOrderIdk__BackingField {
            get {
                return this.WorkOrderIdk__BackingFieldField;
            }
            set {
                if ((this.WorkOrderIdk__BackingFieldField.Equals(value) != true)) {
                    this.WorkOrderIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrderIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDevice", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class UserDevice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TestApp.WorkOrderService.ActiveDevice ActiveDevicek__BackingFieldField;
        
        private TestApp.WorkOrderService.AuthenticationToken AuthenticationTokenk__BackingFieldField;
        
        private TestApp.WorkOrderService.CommunicationPackage[] CommunicationPackagesk__BackingFieldField;
        
        private TestApp.WorkOrderService.DeviceAccessRestriction[] DeviceAccessRestrictionsk__BackingFieldField;
        
        private TestApp.WorkOrderService.DeviceAppInstallation[] DeviceAppInstallationsk__BackingFieldField;
        
        private int DeviceIdk__BackingFieldField;
        
        private int DeviceMemoryResourcek__BackingFieldField;
        
        private int DeviceProcRatingk__BackingFieldField;
        
        private string DeviceTypek__BackingFieldField;
        
        private string GCMCodek__BackingFieldField;
        
        private TestApp.WorkOrderService.User Userk__BackingFieldField;
        
        private string Usernamek__BackingFieldField;
        
        private TestApp.WorkOrderService.WorkOrder[] WorkOrders1k__BackingFieldField;
        
        private TestApp.WorkOrderService.WorkOrder[] WorkOrdersk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ActiveDevice>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.ActiveDevice ActiveDevicek__BackingField {
            get {
                return this.ActiveDevicek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveDevicek__BackingFieldField, value) != true)) {
                    this.ActiveDevicek__BackingFieldField = value;
                    this.RaisePropertyChanged("ActiveDevicek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AuthenticationToken>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.AuthenticationToken AuthenticationTokenk__BackingField {
            get {
                return this.AuthenticationTokenk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenk__BackingFieldField, value) != true)) {
                    this.AuthenticationTokenk__BackingFieldField = value;
                    this.RaisePropertyChanged("AuthenticationTokenk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommunicationPackages>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.CommunicationPackage[] CommunicationPackagesk__BackingField {
            get {
                return this.CommunicationPackagesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationPackagesk__BackingFieldField, value) != true)) {
                    this.CommunicationPackagesk__BackingFieldField = value;
                    this.RaisePropertyChanged("CommunicationPackagesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceAccessRestrictions>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.DeviceAccessRestriction[] DeviceAccessRestrictionsk__BackingField {
            get {
                return this.DeviceAccessRestrictionsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceAccessRestrictionsk__BackingFieldField, value) != true)) {
                    this.DeviceAccessRestrictionsk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceAccessRestrictionsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceAppInstallations>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.DeviceAppInstallation[] DeviceAppInstallationsk__BackingField {
            get {
                return this.DeviceAppInstallationsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceAppInstallationsk__BackingFieldField, value) != true)) {
                    this.DeviceAppInstallationsk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceAppInstallationsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceId>k__BackingField", IsRequired=true)]
        public int DeviceIdk__BackingField {
            get {
                return this.DeviceIdk__BackingFieldField;
            }
            set {
                if ((this.DeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceMemoryResource>k__BackingField", IsRequired=true)]
        public int DeviceMemoryResourcek__BackingField {
            get {
                return this.DeviceMemoryResourcek__BackingFieldField;
            }
            set {
                if ((this.DeviceMemoryResourcek__BackingFieldField.Equals(value) != true)) {
                    this.DeviceMemoryResourcek__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceMemoryResourcek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceProcRating>k__BackingField", IsRequired=true)]
        public int DeviceProcRatingk__BackingField {
            get {
                return this.DeviceProcRatingk__BackingFieldField;
            }
            set {
                if ((this.DeviceProcRatingk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceProcRatingk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceProcRatingk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceType>k__BackingField", IsRequired=true)]
        public string DeviceTypek__BackingField {
            get {
                return this.DeviceTypek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceTypek__BackingFieldField, value) != true)) {
                    this.DeviceTypek__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceTypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GCMCode>k__BackingField", IsRequired=true)]
        public string GCMCodek__BackingField {
            get {
                return this.GCMCodek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GCMCodek__BackingFieldField, value) != true)) {
                    this.GCMCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("GCMCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<User>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.User Userk__BackingField {
            get {
                return this.Userk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Userk__BackingFieldField, value) != true)) {
                    this.Userk__BackingFieldField = value;
                    this.RaisePropertyChanged("Userk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Username>k__BackingField", IsRequired=true)]
        public string Usernamek__BackingField {
            get {
                return this.Usernamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Usernamek__BackingFieldField, value) != true)) {
                    this.Usernamek__BackingFieldField = value;
                    this.RaisePropertyChanged("Usernamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrders1>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.WorkOrder[] WorkOrders1k__BackingField {
            get {
                return this.WorkOrders1k__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrders1k__BackingFieldField, value) != true)) {
                    this.WorkOrders1k__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrders1k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrders>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.WorkOrder[] WorkOrdersk__BackingField {
            get {
                return this.WorkOrdersk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrdersk__BackingFieldField, value) != true)) {
                    this.WorkOrdersk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrdersk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveDevice", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class ActiveDevice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DeviceIdk__BackingFieldField;
        
        private System.DateTime LastActiveSendk__BackingFieldField;
        
        private TestApp.WorkOrderService.UserDevice UserDevicek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceId>k__BackingField", IsRequired=true)]
        public int DeviceIdk__BackingField {
            get {
                return this.DeviceIdk__BackingFieldField;
            }
            set {
                if ((this.DeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastActiveSend>k__BackingField", IsRequired=true)]
        public System.DateTime LastActiveSendk__BackingField {
            get {
                return this.LastActiveSendk__BackingFieldField;
            }
            set {
                if ((this.LastActiveSendk__BackingFieldField.Equals(value) != true)) {
                    this.LastActiveSendk__BackingFieldField = value;
                    this.RaisePropertyChanged("LastActiveSendk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserDevice>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.UserDevice UserDevicek__BackingField {
            get {
                return this.UserDevicek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDevicek__BackingFieldField, value) != true)) {
                    this.UserDevicek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserDevicek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationToken", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class AuthenticationToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreationDatek__BackingFieldField;
        
        private int DeviceIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> LastAccessDatek__BackingFieldField;
        
        private string Tokenk__BackingFieldField;
        
        private TestApp.WorkOrderService.UserDevice UserDevicek__BackingFieldField;
        
        private TestApp.WorkOrderService.User Userk__BackingFieldField;
        
        private string Usernamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreationDate>k__BackingField", IsRequired=true)]
        public System.DateTime CreationDatek__BackingField {
            get {
                return this.CreationDatek__BackingFieldField;
            }
            set {
                if ((this.CreationDatek__BackingFieldField.Equals(value) != true)) {
                    this.CreationDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreationDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceId>k__BackingField", IsRequired=true)]
        public int DeviceIdk__BackingField {
            get {
                return this.DeviceIdk__BackingFieldField;
            }
            set {
                if ((this.DeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastAccessDate>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> LastAccessDatek__BackingField {
            get {
                return this.LastAccessDatek__BackingFieldField;
            }
            set {
                if ((this.LastAccessDatek__BackingFieldField.Equals(value) != true)) {
                    this.LastAccessDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastAccessDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Token>k__BackingField", IsRequired=true)]
        public string Tokenk__BackingField {
            get {
                return this.Tokenk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Tokenk__BackingFieldField, value) != true)) {
                    this.Tokenk__BackingFieldField = value;
                    this.RaisePropertyChanged("Tokenk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserDevice>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.UserDevice UserDevicek__BackingField {
            get {
                return this.UserDevicek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDevicek__BackingFieldField, value) != true)) {
                    this.UserDevicek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserDevicek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<User>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.User Userk__BackingField {
            get {
                return this.Userk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Userk__BackingFieldField, value) != true)) {
                    this.Userk__BackingFieldField = value;
                    this.RaisePropertyChanged("Userk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Username>k__BackingField", IsRequired=true)]
        public string Usernamek__BackingField {
            get {
                return this.Usernamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Usernamek__BackingFieldField, value) != true)) {
                    this.Usernamek__BackingFieldField = value;
                    this.RaisePropertyChanged("Usernamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TestApp.WorkOrderService.AuthenticationToken[] AuthenticationTokensk__BackingFieldField;
        
        private string Forenamek__BackingFieldField;
        
        private string Passwordk__BackingFieldField;
        
        private string Surnamek__BackingFieldField;
        
        private TestApp.WorkOrderService.UserDevice[] UserDevicesk__BackingFieldField;
        
        private int UserIdk__BackingFieldField;
        
        private string Usernamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AuthenticationTokens>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.AuthenticationToken[] AuthenticationTokensk__BackingField {
            get {
                return this.AuthenticationTokensk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokensk__BackingFieldField, value) != true)) {
                    this.AuthenticationTokensk__BackingFieldField = value;
                    this.RaisePropertyChanged("AuthenticationTokensk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Forename>k__BackingField", IsRequired=true)]
        public string Forenamek__BackingField {
            get {
                return this.Forenamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Forenamek__BackingFieldField, value) != true)) {
                    this.Forenamek__BackingFieldField = value;
                    this.RaisePropertyChanged("Forenamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Password>k__BackingField", IsRequired=true)]
        public string Passwordk__BackingField {
            get {
                return this.Passwordk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Passwordk__BackingFieldField, value) != true)) {
                    this.Passwordk__BackingFieldField = value;
                    this.RaisePropertyChanged("Passwordk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Surname>k__BackingField", IsRequired=true)]
        public string Surnamek__BackingField {
            get {
                return this.Surnamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Surnamek__BackingFieldField, value) != true)) {
                    this.Surnamek__BackingFieldField = value;
                    this.RaisePropertyChanged("Surnamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserDevices>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.UserDevice[] UserDevicesk__BackingField {
            get {
                return this.UserDevicesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDevicesk__BackingFieldField, value) != true)) {
                    this.UserDevicesk__BackingFieldField = value;
                    this.RaisePropertyChanged("UserDevicesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserId>k__BackingField", IsRequired=true)]
        public int UserIdk__BackingField {
            get {
                return this.UserIdk__BackingFieldField;
            }
            set {
                if ((this.UserIdk__BackingFieldField.Equals(value) != true)) {
                    this.UserIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("UserIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Username>k__BackingField", IsRequired=true)]
        public string Usernamek__BackingField {
            get {
                return this.Usernamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Usernamek__BackingFieldField, value) != true)) {
                    this.Usernamek__BackingFieldField = value;
                    this.RaisePropertyChanged("Usernamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceAccessRestriction", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class DeviceAccessRestriction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccessRestrictionIdk__BackingFieldField;
        
        private int Dayk__BackingFieldField;
        
        private int DeviceIdk__BackingFieldField;
        
        private System.TimeSpan EndTimek__BackingFieldField;
        
        private System.TimeSpan StartTimek__BackingFieldField;
        
        private TestApp.WorkOrderService.UserDevice UserDevicek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AccessRestrictionId>k__BackingField", IsRequired=true)]
        public int AccessRestrictionIdk__BackingField {
            get {
                return this.AccessRestrictionIdk__BackingFieldField;
            }
            set {
                if ((this.AccessRestrictionIdk__BackingFieldField.Equals(value) != true)) {
                    this.AccessRestrictionIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("AccessRestrictionIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Day>k__BackingField", IsRequired=true)]
        public int Dayk__BackingField {
            get {
                return this.Dayk__BackingFieldField;
            }
            set {
                if ((this.Dayk__BackingFieldField.Equals(value) != true)) {
                    this.Dayk__BackingFieldField = value;
                    this.RaisePropertyChanged("Dayk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceId>k__BackingField", IsRequired=true)]
        public int DeviceIdk__BackingField {
            get {
                return this.DeviceIdk__BackingFieldField;
            }
            set {
                if ((this.DeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EndTime>k__BackingField", IsRequired=true)]
        public System.TimeSpan EndTimek__BackingField {
            get {
                return this.EndTimek__BackingFieldField;
            }
            set {
                if ((this.EndTimek__BackingFieldField.Equals(value) != true)) {
                    this.EndTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("EndTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<StartTime>k__BackingField", IsRequired=true)]
        public System.TimeSpan StartTimek__BackingField {
            get {
                return this.StartTimek__BackingFieldField;
            }
            set {
                if ((this.StartTimek__BackingFieldField.Equals(value) != true)) {
                    this.StartTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("StartTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserDevice>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.UserDevice UserDevicek__BackingField {
            get {
                return this.UserDevicek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDevicek__BackingFieldField, value) != true)) {
                    this.UserDevicek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserDevicek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceAppInstallation", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class DeviceAppInstallation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ApplicationDevicePairIdk__BackingFieldField;
        
        private int ApplicationIdk__BackingFieldField;
        
        private int DeviceIdk__BackingFieldField;
        
        private System.DateTime InstallDatek__BackingFieldField;
        
        private TestApp.WorkOrderService.UserDevice UserDevicek__BackingFieldField;
        
        private TestApp.WorkOrderService.WorkApplication WorkApplicationk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationDevicePairId>k__BackingField", IsRequired=true)]
        public int ApplicationDevicePairIdk__BackingField {
            get {
                return this.ApplicationDevicePairIdk__BackingFieldField;
            }
            set {
                if ((this.ApplicationDevicePairIdk__BackingFieldField.Equals(value) != true)) {
                    this.ApplicationDevicePairIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationDevicePairIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationId>k__BackingField", IsRequired=true)]
        public int ApplicationIdk__BackingField {
            get {
                return this.ApplicationIdk__BackingFieldField;
            }
            set {
                if ((this.ApplicationIdk__BackingFieldField.Equals(value) != true)) {
                    this.ApplicationIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceId>k__BackingField", IsRequired=true)]
        public int DeviceIdk__BackingField {
            get {
                return this.DeviceIdk__BackingFieldField;
            }
            set {
                if ((this.DeviceIdk__BackingFieldField.Equals(value) != true)) {
                    this.DeviceIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<InstallDate>k__BackingField", IsRequired=true)]
        public System.DateTime InstallDatek__BackingField {
            get {
                return this.InstallDatek__BackingFieldField;
            }
            set {
                if ((this.InstallDatek__BackingFieldField.Equals(value) != true)) {
                    this.InstallDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("InstallDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserDevice>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.UserDevice UserDevicek__BackingField {
            get {
                return this.UserDevicek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDevicek__BackingFieldField, value) != true)) {
                    this.UserDevicek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserDevicek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkApplication>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.WorkApplication WorkApplicationk__BackingField {
            get {
                return this.WorkApplicationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkApplicationk__BackingFieldField, value) != true)) {
                    this.WorkApplicationk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkApplicationk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkApplication", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    [System.SerializableAttribute()]
    public partial class WorkApplication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationCreatork__BackingFieldField;
        
        private string ApplicationDescriptionk__BackingFieldField;
        
        private int ApplicationIdk__BackingFieldField;
        
        private string ApplicationNamek__BackingFieldField;
        
        private string ApplicationNamespacek__BackingFieldField;
        
        private string ApplicationPackageURLk__BackingFieldField;
        
        private string ApplicationUIResultIntentk__BackingFieldField;
        
        private int ApplicationVersionk__BackingFieldField;
        
        private string ApplicationWorkIntentk__BackingFieldField;
        
        private TestApp.WorkOrderService.DeviceAppInstallation[] DeviceAppInstallationsk__BackingFieldField;
        
        private TestApp.WorkOrderService.WorkOrder[] WorkOrdersk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationCreator>k__BackingField", IsRequired=true)]
        public string ApplicationCreatork__BackingField {
            get {
                return this.ApplicationCreatork__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationCreatork__BackingFieldField, value) != true)) {
                    this.ApplicationCreatork__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationCreatork__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationDescription>k__BackingField", IsRequired=true)]
        public string ApplicationDescriptionk__BackingField {
            get {
                return this.ApplicationDescriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationDescriptionk__BackingFieldField, value) != true)) {
                    this.ApplicationDescriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationDescriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationId>k__BackingField", IsRequired=true)]
        public int ApplicationIdk__BackingField {
            get {
                return this.ApplicationIdk__BackingFieldField;
            }
            set {
                if ((this.ApplicationIdk__BackingFieldField.Equals(value) != true)) {
                    this.ApplicationIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationName>k__BackingField", IsRequired=true)]
        public string ApplicationNamek__BackingField {
            get {
                return this.ApplicationNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNamek__BackingFieldField, value) != true)) {
                    this.ApplicationNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationNamespace>k__BackingField", IsRequired=true)]
        public string ApplicationNamespacek__BackingField {
            get {
                return this.ApplicationNamespacek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNamespacek__BackingFieldField, value) != true)) {
                    this.ApplicationNamespacek__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationNamespacek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationPackageURL>k__BackingField", IsRequired=true)]
        public string ApplicationPackageURLk__BackingField {
            get {
                return this.ApplicationPackageURLk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationPackageURLk__BackingFieldField, value) != true)) {
                    this.ApplicationPackageURLk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationPackageURLk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationUIResultIntent>k__BackingField", IsRequired=true)]
        public string ApplicationUIResultIntentk__BackingField {
            get {
                return this.ApplicationUIResultIntentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationUIResultIntentk__BackingFieldField, value) != true)) {
                    this.ApplicationUIResultIntentk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationUIResultIntentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationVersion>k__BackingField", IsRequired=true)]
        public int ApplicationVersionk__BackingField {
            get {
                return this.ApplicationVersionk__BackingFieldField;
            }
            set {
                if ((this.ApplicationVersionk__BackingFieldField.Equals(value) != true)) {
                    this.ApplicationVersionk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationVersionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ApplicationWorkIntent>k__BackingField", IsRequired=true)]
        public string ApplicationWorkIntentk__BackingField {
            get {
                return this.ApplicationWorkIntentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationWorkIntentk__BackingFieldField, value) != true)) {
                    this.ApplicationWorkIntentk__BackingFieldField = value;
                    this.RaisePropertyChanged("ApplicationWorkIntentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DeviceAppInstallations>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.DeviceAppInstallation[] DeviceAppInstallationsk__BackingField {
            get {
                return this.DeviceAppInstallationsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceAppInstallationsk__BackingFieldField, value) != true)) {
                    this.DeviceAppInstallationsk__BackingFieldField = value;
                    this.RaisePropertyChanged("DeviceAppInstallationsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WorkOrders>k__BackingField", IsRequired=true)]
        public TestApp.WorkOrderService.WorkOrder[] WorkOrdersk__BackingField {
            get {
                return this.WorkOrdersk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkOrdersk__BackingFieldField, value) != true)) {
                    this.WorkOrdersk__BackingFieldField = value;
                    this.RaisePropertyChanged("WorkOrdersk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkOrderService.IWorkOrderSvc")]
    public interface IWorkOrderSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrderSvc/CreateWorkOrder", ReplyAction="http://tempuri.org/IWorkOrderSvc/CreateWorkOrderResponse")]
        TestApp.WorkOrderService.WorkOrder CreateWorkOrder(string at, int deviceId, int applicationId, TestApp.WorkOrderService.CommPackageParamListItem[] paramList, string backgroundProcessFunction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrderSvc/CancelWorkOrder", ReplyAction="http://tempuri.org/IWorkOrderSvc/CancelWorkOrderResponse")]
        void CancelWorkOrder(string at, int workOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrderSvc/GetWorkOrder", ReplyAction="http://tempuri.org/IWorkOrderSvc/GetWorkOrderResponse")]
        TestApp.WorkOrderService.WorkOrderTrimmed GetWorkOrder(string at, int deviceId, int workOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrderSvc/AcknowledgeWorkOrder", ReplyAction="http://tempuri.org/IWorkOrderSvc/AcknowledgeWorkOrderResponse")]
        void AcknowledgeWorkOrder(string at, int workOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrderSvc/SubmitWorkOrderResult", ReplyAction="http://tempuri.org/IWorkOrderSvc/SubmitWorkOrderResultResponse")]
        void SubmitWorkOrderResult(string at, int workOrderId, string resultJson, System.DateTime compuatationStartTime, System.DateTime computationEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkOrderSvc/MarkWorkOrderInComputation", ReplyAction="http://tempuri.org/IWorkOrderSvc/MarkWorkOrderInComputationResponse")]
        void MarkWorkOrderInComputation(string at, int workOrderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkOrderSvcChannel : TestApp.WorkOrderService.IWorkOrderSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkOrderSvcClient : System.ServiceModel.ClientBase<TestApp.WorkOrderService.IWorkOrderSvc>, TestApp.WorkOrderService.IWorkOrderSvc {
        
        public WorkOrderSvcClient() {
        }
        
        public WorkOrderSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkOrderSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkOrderSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkOrderSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestApp.WorkOrderService.WorkOrder CreateWorkOrder(string at, int deviceId, int applicationId, TestApp.WorkOrderService.CommPackageParamListItem[] paramList, string backgroundProcessFunction) {
            return base.Channel.CreateWorkOrder(at, deviceId, applicationId, paramList, backgroundProcessFunction);
        }
        
        public void CancelWorkOrder(string at, int workOrderId) {
            base.Channel.CancelWorkOrder(at, workOrderId);
        }
        
        public TestApp.WorkOrderService.WorkOrderTrimmed GetWorkOrder(string at, int deviceId, int workOrderId) {
            return base.Channel.GetWorkOrder(at, deviceId, workOrderId);
        }
        
        public void AcknowledgeWorkOrder(string at, int workOrderId) {
            base.Channel.AcknowledgeWorkOrder(at, workOrderId);
        }
        
        public void SubmitWorkOrderResult(string at, int workOrderId, string resultJson, System.DateTime compuatationStartTime, System.DateTime computationEndTime) {
            base.Channel.SubmitWorkOrderResult(at, workOrderId, resultJson, compuatationStartTime, computationEndTime);
        }
        
        public void MarkWorkOrderInComputation(string at, int workOrderId) {
            base.Channel.MarkWorkOrderInComputation(at, workOrderId);
        }
    }
}
