//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace ComputeAndroidApp.UserWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IUserSvc", Namespace="http://tempuri.org/")]
    public partial class UserSvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUserDeviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUserDeviceNoGCMCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserDeviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyUserDeviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeviceIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTestNotificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkDeviceActiveOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarkDeviceInactiveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserSvc() {
            this.Url = "http://c4b0eba7dae642f38a424487179f8540.cloudapp.net/UserSvc.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;
        
        /// <remarks/>
        public event ModifyUserCompletedEventHandler ModifyUserCompleted;
        
        /// <remarks/>
        public event AddUserDeviceCompletedEventHandler AddUserDeviceCompleted;
        
        /// <remarks/>
        public event AddUserDeviceNoGCMCodeCompletedEventHandler AddUserDeviceNoGCMCodeCompleted;
        
        /// <remarks/>
        public event DeleteUserDeviceCompletedEventHandler DeleteUserDeviceCompleted;
        
        /// <remarks/>
        public event ModifyUserDeviceCompletedEventHandler ModifyUserDeviceCompleted;
        
        /// <remarks/>
        public event GetDeviceIdCompletedEventHandler GetDeviceIdCompleted;
        
        /// <remarks/>
        public event SendTestNotificationCompletedEventHandler SendTestNotificationCompleted;
        
        /// <remarks/>
        public event MarkDeviceActiveCompletedEventHandler MarkDeviceActiveCompleted;
        
        /// <remarks/>
        public event MarkDeviceInactiveCompletedEventHandler MarkDeviceInactiveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/AddUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public User AddUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string forename, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string surname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            object[] results = this.Invoke("AddUser", new object[] {
                        forename,
                        surname,
                        username,
                        password});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserAsync(string forename, string surname, string username, string password) {
            this.AddUserAsync(forename, surname, username, password, null);
        }
        
        /// <remarks/>
        public void AddUserAsync(string forename, string surname, string username, string password, object userState) {
            if ((this.AddUserOperationCompleted == null)) {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                        forename,
                        surname,
                        username,
                        password}, this.AddUserOperationCompleted, userState);
        }
        
        private void OnAddUserOperationCompleted(object arg) {
            if ((this.AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/ModifyUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModifyUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int userId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool userIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string forename, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string surname, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            this.Invoke("ModifyUser", new object[] {
                        at,
                        userId,
                        userIdSpecified,
                        forename,
                        surname,
                        password});
        }
        
        /// <remarks/>
        public void ModifyUserAsync(string at, int userId, bool userIdSpecified, string forename, string surname, string password) {
            this.ModifyUserAsync(at, userId, userIdSpecified, forename, surname, password, null);
        }
        
        /// <remarks/>
        public void ModifyUserAsync(string at, int userId, bool userIdSpecified, string forename, string surname, string password, object userState) {
            if ((this.ModifyUserOperationCompleted == null)) {
                this.ModifyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyUserOperationCompleted);
            }
            this.InvokeAsync("ModifyUser", new object[] {
                        at,
                        userId,
                        userIdSpecified,
                        forename,
                        surname,
                        password}, this.ModifyUserOperationCompleted, userState);
        }
        
        private void OnModifyUserOperationCompleted(object arg) {
            if ((this.ModifyUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/AddUserDevice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserDevice AddUserDevice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceType, int deviceMemoryResource, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceMemoryResourceSpecified, int deviceProcRating, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceProcRatingSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gcmCode) {
            object[] results = this.Invoke("AddUserDevice", new object[] {
                        at,
                        deviceType,
                        deviceMemoryResource,
                        deviceMemoryResourceSpecified,
                        deviceProcRating,
                        deviceProcRatingSpecified,
                        gcmCode});
            return ((UserDevice)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserDeviceAsync(string at, string deviceType, int deviceMemoryResource, bool deviceMemoryResourceSpecified, int deviceProcRating, bool deviceProcRatingSpecified, string gcmCode) {
            this.AddUserDeviceAsync(at, deviceType, deviceMemoryResource, deviceMemoryResourceSpecified, deviceProcRating, deviceProcRatingSpecified, gcmCode, null);
        }
        
        /// <remarks/>
        public void AddUserDeviceAsync(string at, string deviceType, int deviceMemoryResource, bool deviceMemoryResourceSpecified, int deviceProcRating, bool deviceProcRatingSpecified, string gcmCode, object userState) {
            if ((this.AddUserDeviceOperationCompleted == null)) {
                this.AddUserDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserDeviceOperationCompleted);
            }
            this.InvokeAsync("AddUserDevice", new object[] {
                        at,
                        deviceType,
                        deviceMemoryResource,
                        deviceMemoryResourceSpecified,
                        deviceProcRating,
                        deviceProcRatingSpecified,
                        gcmCode}, this.AddUserDeviceOperationCompleted, userState);
        }
        
        private void OnAddUserDeviceOperationCompleted(object arg) {
            if ((this.AddUserDeviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserDeviceCompleted(this, new AddUserDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/AddUserDeviceNoGCMCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserDevice AddUserDeviceNoGCMCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceType, int deviceMemoryResource, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceMemoryResourceSpecified, int deviceProcRating, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceProcRatingSpecified) {
            object[] results = this.Invoke("AddUserDeviceNoGCMCode", new object[] {
                        at,
                        username,
                        deviceType,
                        deviceMemoryResource,
                        deviceMemoryResourceSpecified,
                        deviceProcRating,
                        deviceProcRatingSpecified});
            return ((UserDevice)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserDeviceNoGCMCodeAsync(string at, string username, string deviceType, int deviceMemoryResource, bool deviceMemoryResourceSpecified, int deviceProcRating, bool deviceProcRatingSpecified) {
            this.AddUserDeviceNoGCMCodeAsync(at, username, deviceType, deviceMemoryResource, deviceMemoryResourceSpecified, deviceProcRating, deviceProcRatingSpecified, null);
        }
        
        /// <remarks/>
        public void AddUserDeviceNoGCMCodeAsync(string at, string username, string deviceType, int deviceMemoryResource, bool deviceMemoryResourceSpecified, int deviceProcRating, bool deviceProcRatingSpecified, object userState) {
            if ((this.AddUserDeviceNoGCMCodeOperationCompleted == null)) {
                this.AddUserDeviceNoGCMCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserDeviceNoGCMCodeOperationCompleted);
            }
            this.InvokeAsync("AddUserDeviceNoGCMCode", new object[] {
                        at,
                        username,
                        deviceType,
                        deviceMemoryResource,
                        deviceMemoryResourceSpecified,
                        deviceProcRating,
                        deviceProcRatingSpecified}, this.AddUserDeviceNoGCMCodeOperationCompleted, userState);
        }
        
        private void OnAddUserDeviceNoGCMCodeOperationCompleted(object arg) {
            if ((this.AddUserDeviceNoGCMCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserDeviceNoGCMCodeCompleted(this, new AddUserDeviceNoGCMCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/DeleteUserDevice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUserDevice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified) {
            this.Invoke("DeleteUserDevice", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified});
        }
        
        /// <remarks/>
        public void DeleteUserDeviceAsync(string at, int deviceId, bool deviceIdSpecified) {
            this.DeleteUserDeviceAsync(at, deviceId, deviceIdSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteUserDeviceAsync(string at, int deviceId, bool deviceIdSpecified, object userState) {
            if ((this.DeleteUserDeviceOperationCompleted == null)) {
                this.DeleteUserDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserDeviceOperationCompleted);
            }
            this.InvokeAsync("DeleteUserDevice", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified}, this.DeleteUserDeviceOperationCompleted, userState);
        }
        
        private void OnDeleteUserDeviceOperationCompleted(object arg) {
            if ((this.DeleteUserDeviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserDeviceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/ModifyUserDevice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModifyUserDevice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gcmCode, int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified) {
            this.Invoke("ModifyUserDevice", new object[] {
                        at,
                        gcmCode,
                        deviceId,
                        deviceIdSpecified});
        }
        
        /// <remarks/>
        public void ModifyUserDeviceAsync(string at, string gcmCode, int deviceId, bool deviceIdSpecified) {
            this.ModifyUserDeviceAsync(at, gcmCode, deviceId, deviceIdSpecified, null);
        }
        
        /// <remarks/>
        public void ModifyUserDeviceAsync(string at, string gcmCode, int deviceId, bool deviceIdSpecified, object userState) {
            if ((this.ModifyUserDeviceOperationCompleted == null)) {
                this.ModifyUserDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyUserDeviceOperationCompleted);
            }
            this.InvokeAsync("ModifyUserDevice", new object[] {
                        at,
                        gcmCode,
                        deviceId,
                        deviceIdSpecified}, this.ModifyUserDeviceOperationCompleted, userState);
        }
        
        private void OnModifyUserDeviceOperationCompleted(object arg) {
            if ((this.ModifyUserDeviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyUserDeviceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/GetDeviceId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetDeviceId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string gcmId, out int GetDeviceIdResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetDeviceIdResultSpecified) {
            object[] results = this.Invoke("GetDeviceId", new object[] {
                        at,
                        gcmId});
            GetDeviceIdResult = ((int)(results[0]));
            GetDeviceIdResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GetDeviceIdAsync(string at, string gcmId) {
            this.GetDeviceIdAsync(at, gcmId, null);
        }
        
        /// <remarks/>
        public void GetDeviceIdAsync(string at, string gcmId, object userState) {
            if ((this.GetDeviceIdOperationCompleted == null)) {
                this.GetDeviceIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeviceIdOperationCompleted);
            }
            this.InvokeAsync("GetDeviceId", new object[] {
                        at,
                        gcmId}, this.GetDeviceIdOperationCompleted, userState);
        }
        
        private void OnGetDeviceIdOperationCompleted(object arg) {
            if ((this.GetDeviceIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeviceIdCompleted(this, new GetDeviceIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/SendTestNotification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendTestNotification(int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified) {
            this.Invoke("SendTestNotification", new object[] {
                        deviceId,
                        deviceIdSpecified});
        }
        
        /// <remarks/>
        public void SendTestNotificationAsync(int deviceId, bool deviceIdSpecified) {
            this.SendTestNotificationAsync(deviceId, deviceIdSpecified, null);
        }
        
        /// <remarks/>
        public void SendTestNotificationAsync(int deviceId, bool deviceIdSpecified, object userState) {
            if ((this.SendTestNotificationOperationCompleted == null)) {
                this.SendTestNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTestNotificationOperationCompleted);
            }
            this.InvokeAsync("SendTestNotification", new object[] {
                        deviceId,
                        deviceIdSpecified}, this.SendTestNotificationOperationCompleted, userState);
        }
        
        private void OnSendTestNotificationOperationCompleted(object arg) {
            if ((this.SendTestNotificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTestNotificationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/MarkDeviceActive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MarkDeviceActive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified) {
            this.Invoke("MarkDeviceActive", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified});
        }
        
        /// <remarks/>
        public void MarkDeviceActiveAsync(string at, int deviceId, bool deviceIdSpecified) {
            this.MarkDeviceActiveAsync(at, deviceId, deviceIdSpecified, null);
        }
        
        /// <remarks/>
        public void MarkDeviceActiveAsync(string at, int deviceId, bool deviceIdSpecified, object userState) {
            if ((this.MarkDeviceActiveOperationCompleted == null)) {
                this.MarkDeviceActiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkDeviceActiveOperationCompleted);
            }
            this.InvokeAsync("MarkDeviceActive", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified}, this.MarkDeviceActiveOperationCompleted, userState);
        }
        
        private void OnMarkDeviceActiveOperationCompleted(object arg) {
            if ((this.MarkDeviceActiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkDeviceActiveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IUserSvc/MarkDeviceInactive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MarkDeviceInactive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string at, int deviceId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool deviceIdSpecified) {
            this.Invoke("MarkDeviceInactive", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified});
        }
        
        /// <remarks/>
        public void MarkDeviceInactiveAsync(string at, int deviceId, bool deviceIdSpecified) {
            this.MarkDeviceInactiveAsync(at, deviceId, deviceIdSpecified, null);
        }
        
        /// <remarks/>
        public void MarkDeviceInactiveAsync(string at, int deviceId, bool deviceIdSpecified, object userState) {
            if ((this.MarkDeviceInactiveOperationCompleted == null)) {
                this.MarkDeviceInactiveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkDeviceInactiveOperationCompleted);
            }
            this.InvokeAsync("MarkDeviceInactive", new object[] {
                        at,
                        deviceId,
                        deviceIdSpecified}, this.MarkDeviceInactiveOperationCompleted, userState);
        }
        
        private void OnMarkDeviceInactiveOperationCompleted(object arg) {
            if ((this.MarkDeviceInactiveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkDeviceInactiveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class User {
        
        private AuthenticationToken[] authenticationTokensk__BackingFieldField;
        
        private string forenamek__BackingFieldField;
        
        private string passwordk__BackingFieldField;
        
        private string surnamek__BackingFieldField;
        
        private UserDevice[] userDevicesk__BackingFieldField;
        
        private int userIdk__BackingFieldField;
        
        private string usernamek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<AuthenticationTokens>k__BackingField", IsNullable=true)]
        public AuthenticationToken[] AuthenticationTokensk__BackingField {
            get {
                return this.authenticationTokensk__BackingFieldField;
            }
            set {
                this.authenticationTokensk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Forename>k__BackingField", IsNullable=true)]
        public string Forenamek__BackingField {
            get {
                return this.forenamek__BackingFieldField;
            }
            set {
                this.forenamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Password>k__BackingField", IsNullable=true)]
        public string Passwordk__BackingField {
            get {
                return this.passwordk__BackingFieldField;
            }
            set {
                this.passwordk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Surname>k__BackingField", IsNullable=true)]
        public string Surnamek__BackingField {
            get {
                return this.surnamek__BackingFieldField;
            }
            set {
                this.surnamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<UserDevices>k__BackingField", IsNullable=true)]
        public UserDevice[] UserDevicesk__BackingField {
            get {
                return this.userDevicesk__BackingFieldField;
            }
            set {
                this.userDevicesk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserId>k__BackingField")]
        public int UserIdk__BackingField {
            get {
                return this.userIdk__BackingFieldField;
            }
            set {
                this.userIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Username>k__BackingField", IsNullable=true)]
        public string Usernamek__BackingField {
            get {
                return this.usernamek__BackingFieldField;
            }
            set {
                this.usernamek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class AuthenticationToken {
        
        private System.DateTime creationDatek__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> lastAccessDatek__BackingFieldField;
        
        private string tokenk__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        private User userk__BackingFieldField;
        
        private string usernamek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CreationDate>k__BackingField")]
        public System.DateTime CreationDatek__BackingField {
            get {
                return this.creationDatek__BackingFieldField;
            }
            set {
                this.creationDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastAccessDate>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> LastAccessDatek__BackingField {
            get {
                return this.lastAccessDatek__BackingFieldField;
            }
            set {
                this.lastAccessDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Token>k__BackingField", IsNullable=true)]
        public string Tokenk__BackingField {
            get {
                return this.tokenk__BackingFieldField;
            }
            set {
                this.tokenk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<User>k__BackingField", IsNullable=true)]
        public User Userk__BackingField {
            get {
                return this.userk__BackingFieldField;
            }
            set {
                this.userk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Username>k__BackingField", IsNullable=true)]
        public string Usernamek__BackingField {
            get {
                return this.usernamek__BackingFieldField;
            }
            set {
                this.usernamek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class UserDevice {
        
        private ActiveDevice activeDevicek__BackingFieldField;
        
        private AuthenticationToken authenticationTokenk__BackingFieldField;
        
        private CommunicationPackage[] communicationPackagesk__BackingFieldField;
        
        private DeviceAccessRestriction[] deviceAccessRestrictionsk__BackingFieldField;
        
        private DeviceAppInstallation[] deviceAppInstallationsk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private int deviceMemoryResourcek__BackingFieldField;
        
        private int deviceProcRatingk__BackingFieldField;
        
        private string deviceTypek__BackingFieldField;
        
        private string gCMCodek__BackingFieldField;
        
        private User userk__BackingFieldField;
        
        private string usernamek__BackingFieldField;
        
        private WorkOrder[] workOrders1k__BackingFieldField;
        
        private WorkOrder[] workOrdersk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ActiveDevice>k__BackingField", IsNullable=true)]
        public ActiveDevice ActiveDevicek__BackingField {
            get {
                return this.activeDevicek__BackingFieldField;
            }
            set {
                this.activeDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<AuthenticationToken>k__BackingField", IsNullable=true)]
        public AuthenticationToken AuthenticationTokenk__BackingField {
            get {
                return this.authenticationTokenk__BackingFieldField;
            }
            set {
                this.authenticationTokenk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<CommunicationPackages>k__BackingField", IsNullable=true)]
        public CommunicationPackage[] CommunicationPackagesk__BackingField {
            get {
                return this.communicationPackagesk__BackingFieldField;
            }
            set {
                this.communicationPackagesk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<DeviceAccessRestrictions>k__BackingField", IsNullable=true)]
        public DeviceAccessRestriction[] DeviceAccessRestrictionsk__BackingField {
            get {
                return this.deviceAccessRestrictionsk__BackingFieldField;
            }
            set {
                this.deviceAccessRestrictionsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<DeviceAppInstallations>k__BackingField", IsNullable=true)]
        public DeviceAppInstallation[] DeviceAppInstallationsk__BackingField {
            get {
                return this.deviceAppInstallationsk__BackingFieldField;
            }
            set {
                this.deviceAppInstallationsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceMemoryResource>k__BackingField")]
        public int DeviceMemoryResourcek__BackingField {
            get {
                return this.deviceMemoryResourcek__BackingFieldField;
            }
            set {
                this.deviceMemoryResourcek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceProcRating>k__BackingField")]
        public int DeviceProcRatingk__BackingField {
            get {
                return this.deviceProcRatingk__BackingFieldField;
            }
            set {
                this.deviceProcRatingk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceType>k__BackingField", IsNullable=true)]
        public string DeviceTypek__BackingField {
            get {
                return this.deviceTypek__BackingFieldField;
            }
            set {
                this.deviceTypek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<GCMCode>k__BackingField", IsNullable=true)]
        public string GCMCodek__BackingField {
            get {
                return this.gCMCodek__BackingFieldField;
            }
            set {
                this.gCMCodek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<User>k__BackingField", IsNullable=true)]
        public User Userk__BackingField {
            get {
                return this.userk__BackingFieldField;
            }
            set {
                this.userk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Username>k__BackingField", IsNullable=true)]
        public string Usernamek__BackingField {
            get {
                return this.usernamek__BackingFieldField;
            }
            set {
                this.usernamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<WorkOrders1>k__BackingField", IsNullable=true)]
        public WorkOrder[] WorkOrders1k__BackingField {
            get {
                return this.workOrders1k__BackingFieldField;
            }
            set {
                this.workOrders1k__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<WorkOrders>k__BackingField", IsNullable=true)]
        public WorkOrder[] WorkOrdersk__BackingField {
            get {
                return this.workOrdersk__BackingFieldField;
            }
            set {
                this.workOrdersk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class ActiveDevice {
        
        private int deviceIdk__BackingFieldField;
        
        private System.DateTime lastActiveSendk__BackingFieldField;
        
        private System.DateTime lastFetchk__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastActiveSend>k__BackingField")]
        public System.DateTime LastActiveSendk__BackingField {
            get {
                return this.lastActiveSendk__BackingFieldField;
            }
            set {
                this.lastActiveSendk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LastFetch>k__BackingField")]
        public System.DateTime LastFetchk__BackingField {
            get {
                return this.lastFetchk__BackingFieldField;
            }
            set {
                this.lastFetchk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class WorkOrder {
        
        private int applicationIdk__BackingFieldField;
        
        private string commPackageJsonk__BackingFieldField;
        
        private CommunicationPackage[] communicationPackagesk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> endComputationTimek__BackingFieldField;
        
        private int localDeviceIdk__BackingFieldField;
        
        private System.DateTime receiveTimek__BackingFieldField;
        
        private System.Nullable<System.DateTime> slaveWorkOrderLastCommunicationk__BackingFieldField;
        
        private System.Nullable<int> slaveWorkerIdk__BackingFieldField;
        
        private System.Nullable<System.DateTime> slaveWorkerSubmitk__BackingFieldField;
        
        private System.Nullable<System.DateTime> startComputationTimek__BackingFieldField;
        
        private UserDevice userDevice1k__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        private WorkApplication workApplicationk__BackingFieldField;
        
        private int workOrderIdk__BackingFieldField;
        
        private string workOrderResultJsonk__BackingFieldField;
        
        private string workOrderStatusk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationId>k__BackingField")]
        public int ApplicationIdk__BackingField {
            get {
                return this.applicationIdk__BackingFieldField;
            }
            set {
                this.applicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CommPackageJson>k__BackingField", IsNullable=true)]
        public string CommPackageJsonk__BackingField {
            get {
                return this.commPackageJsonk__BackingFieldField;
            }
            set {
                this.commPackageJsonk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<CommunicationPackages>k__BackingField", IsNullable=true)]
        public CommunicationPackage[] CommunicationPackagesk__BackingField {
            get {
                return this.communicationPackagesk__BackingFieldField;
            }
            set {
                this.communicationPackagesk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<EndComputationTime>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> EndComputationTimek__BackingField {
            get {
                return this.endComputationTimek__BackingFieldField;
            }
            set {
                this.endComputationTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<LocalDeviceId>k__BackingField")]
        public int LocalDeviceIdk__BackingField {
            get {
                return this.localDeviceIdk__BackingFieldField;
            }
            set {
                this.localDeviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ReceiveTime>k__BackingField")]
        public System.DateTime ReceiveTimek__BackingField {
            get {
                return this.receiveTimek__BackingFieldField;
            }
            set {
                this.receiveTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkOrderLastCommunication>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> SlaveWorkOrderLastCommunicationk__BackingField {
            get {
                return this.slaveWorkOrderLastCommunicationk__BackingFieldField;
            }
            set {
                this.slaveWorkOrderLastCommunicationk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkerId>k__BackingField", IsNullable=true)]
        public System.Nullable<int> SlaveWorkerIdk__BackingField {
            get {
                return this.slaveWorkerIdk__BackingFieldField;
            }
            set {
                this.slaveWorkerIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SlaveWorkerSubmit>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> SlaveWorkerSubmitk__BackingField {
            get {
                return this.slaveWorkerSubmitk__BackingFieldField;
            }
            set {
                this.slaveWorkerSubmitk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StartComputationTime>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> StartComputationTimek__BackingField {
            get {
                return this.startComputationTimek__BackingFieldField;
            }
            set {
                this.startComputationTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice1>k__BackingField", IsNullable=true)]
        public UserDevice UserDevice1k__BackingField {
            get {
                return this.userDevice1k__BackingFieldField;
            }
            set {
                this.userDevice1k__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkApplication>k__BackingField", IsNullable=true)]
        public WorkApplication WorkApplicationk__BackingField {
            get {
                return this.workApplicationk__BackingFieldField;
            }
            set {
                this.workApplicationk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderId>k__BackingField")]
        public int WorkOrderIdk__BackingField {
            get {
                return this.workOrderIdk__BackingFieldField;
            }
            set {
                this.workOrderIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderResultJson>k__BackingField", IsNullable=true)]
        public string WorkOrderResultJsonk__BackingField {
            get {
                return this.workOrderResultJsonk__BackingFieldField;
            }
            set {
                this.workOrderResultJsonk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderStatus>k__BackingField", IsNullable=true)]
        public string WorkOrderStatusk__BackingField {
            get {
                return this.workOrderStatusk__BackingFieldField;
            }
            set {
                this.workOrderStatusk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class CommunicationPackage {
        
        private int communicationIdk__BackingFieldField;
        
        private int communicationTypek__BackingFieldField;
        
        private System.Nullable<System.DateTime> dateAcknowledgedk__BackingFieldField;
        
        private string responsek__BackingFieldField;
        
        private int sendAttemptsk__BackingFieldField;
        
        private string statusk__BackingFieldField;
        
        private System.DateTime submitDatek__BackingFieldField;
        
        private int targetDeviceIdk__BackingFieldField;
        
        private System.Nullable<int> workOrderIdk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CommunicationId>k__BackingField")]
        public int CommunicationIdk__BackingField {
            get {
                return this.communicationIdk__BackingFieldField;
            }
            set {
                this.communicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<CommunicationType>k__BackingField")]
        public int CommunicationTypek__BackingField {
            get {
                return this.communicationTypek__BackingFieldField;
            }
            set {
                this.communicationTypek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DateAcknowledged>k__BackingField", IsNullable=true)]
        public System.Nullable<System.DateTime> DateAcknowledgedk__BackingField {
            get {
                return this.dateAcknowledgedk__BackingFieldField;
            }
            set {
                this.dateAcknowledgedk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Response>k__BackingField", IsNullable=true)]
        public string Responsek__BackingField {
            get {
                return this.responsek__BackingFieldField;
            }
            set {
                this.responsek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SendAttempts>k__BackingField")]
        public int SendAttemptsk__BackingField {
            get {
                return this.sendAttemptsk__BackingFieldField;
            }
            set {
                this.sendAttemptsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Status>k__BackingField", IsNullable=true)]
        public string Statusk__BackingField {
            get {
                return this.statusk__BackingFieldField;
            }
            set {
                this.statusk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<SubmitDate>k__BackingField")]
        public System.DateTime SubmitDatek__BackingField {
            get {
                return this.submitDatek__BackingFieldField;
            }
            set {
                this.submitDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<TargetDeviceId>k__BackingField")]
        public int TargetDeviceIdk__BackingField {
            get {
                return this.targetDeviceIdk__BackingFieldField;
            }
            set {
                this.targetDeviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkOrderId>k__BackingField", IsNullable=true)]
        public System.Nullable<int> WorkOrderIdk__BackingField {
            get {
                return this.workOrderIdk__BackingFieldField;
            }
            set {
                this.workOrderIdk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class WorkApplication {
        
        private string applicationCreatork__BackingFieldField;
        
        private string applicationDescriptionk__BackingFieldField;
        
        private int applicationIdk__BackingFieldField;
        
        private string applicationNamek__BackingFieldField;
        
        private string applicationNamespacek__BackingFieldField;
        
        private string applicationPackageURLk__BackingFieldField;
        
        private string applicationUIResultIntentk__BackingFieldField;
        
        private int applicationVersionk__BackingFieldField;
        
        private string applicationWorkIntentk__BackingFieldField;
        
        private DeviceAppInstallation[] deviceAppInstallationsk__BackingFieldField;
        
        private WorkOrder[] workOrdersk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationCreator>k__BackingField", IsNullable=true)]
        public string ApplicationCreatork__BackingField {
            get {
                return this.applicationCreatork__BackingFieldField;
            }
            set {
                this.applicationCreatork__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationDescription>k__BackingField", IsNullable=true)]
        public string ApplicationDescriptionk__BackingField {
            get {
                return this.applicationDescriptionk__BackingFieldField;
            }
            set {
                this.applicationDescriptionk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationId>k__BackingField")]
        public int ApplicationIdk__BackingField {
            get {
                return this.applicationIdk__BackingFieldField;
            }
            set {
                this.applicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationName>k__BackingField", IsNullable=true)]
        public string ApplicationNamek__BackingField {
            get {
                return this.applicationNamek__BackingFieldField;
            }
            set {
                this.applicationNamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationNamespace>k__BackingField", IsNullable=true)]
        public string ApplicationNamespacek__BackingField {
            get {
                return this.applicationNamespacek__BackingFieldField;
            }
            set {
                this.applicationNamespacek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationPackageURL>k__BackingField", IsNullable=true)]
        public string ApplicationPackageURLk__BackingField {
            get {
                return this.applicationPackageURLk__BackingFieldField;
            }
            set {
                this.applicationPackageURLk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationUIResultIntent>k__BackingField", IsNullable=true)]
        public string ApplicationUIResultIntentk__BackingField {
            get {
                return this.applicationUIResultIntentk__BackingFieldField;
            }
            set {
                this.applicationUIResultIntentk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationVersion>k__BackingField")]
        public int ApplicationVersionk__BackingField {
            get {
                return this.applicationVersionk__BackingFieldField;
            }
            set {
                this.applicationVersionk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationWorkIntent>k__BackingField", IsNullable=true)]
        public string ApplicationWorkIntentk__BackingField {
            get {
                return this.applicationWorkIntentk__BackingFieldField;
            }
            set {
                this.applicationWorkIntentk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<DeviceAppInstallations>k__BackingField", IsNullable=true)]
        public DeviceAppInstallation[] DeviceAppInstallationsk__BackingField {
            get {
                return this.deviceAppInstallationsk__BackingFieldField;
            }
            set {
                this.deviceAppInstallationsk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<WorkOrders>k__BackingField", IsNullable=true)]
        public WorkOrder[] WorkOrdersk__BackingField {
            get {
                return this.workOrdersk__BackingFieldField;
            }
            set {
                this.workOrdersk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class DeviceAppInstallation {
        
        private int applicationDevicePairIdk__BackingFieldField;
        
        private int applicationIdk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private System.DateTime installDatek__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        private WorkApplication workApplicationk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationDevicePairId>k__BackingField")]
        public int ApplicationDevicePairIdk__BackingField {
            get {
                return this.applicationDevicePairIdk__BackingFieldField;
            }
            set {
                this.applicationDevicePairIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ApplicationId>k__BackingField")]
        public int ApplicationIdk__BackingField {
            get {
                return this.applicationIdk__BackingFieldField;
            }
            set {
                this.applicationIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<InstallDate>k__BackingField")]
        public System.DateTime InstallDatek__BackingField {
            get {
                return this.installDatek__BackingFieldField;
            }
            set {
                this.installDatek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<WorkApplication>k__BackingField", IsNullable=true)]
        public WorkApplication WorkApplicationk__BackingField {
            get {
                return this.workApplicationk__BackingFieldField;
            }
            set {
                this.workApplicationk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer")]
    public partial class DeviceAccessRestriction {
        
        private int accessRestrictionIdk__BackingFieldField;
        
        private int dayk__BackingFieldField;
        
        private int deviceIdk__BackingFieldField;
        
        private string endTimek__BackingFieldField;
        
        private string startTimek__BackingFieldField;
        
        private UserDevice userDevicek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<AccessRestrictionId>k__BackingField")]
        public int AccessRestrictionIdk__BackingField {
            get {
                return this.accessRestrictionIdk__BackingFieldField;
            }
            set {
                this.accessRestrictionIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Day>k__BackingField")]
        public int Dayk__BackingField {
            get {
                return this.dayk__BackingFieldField;
            }
            set {
                this.dayk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DeviceId>k__BackingField")]
        public int DeviceIdk__BackingField {
            get {
                return this.deviceIdk__BackingFieldField;
            }
            set {
                this.deviceIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<EndTime>k__BackingField", DataType="duration")]
        public string EndTimek__BackingField {
            get {
                return this.endTimek__BackingFieldField;
            }
            set {
                this.endTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StartTime>k__BackingField", DataType="duration")]
        public string StartTimek__BackingField {
            get {
                return this.startTimek__BackingFieldField;
            }
            set {
                this.startTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UserDevice>k__BackingField", IsNullable=true)]
        public UserDevice UserDevicek__BackingField {
            get {
                return this.userDevicek__BackingFieldField;
            }
            set {
                this.userDevicek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ModifyUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddUserDeviceCompletedEventHandler(object sender, AddUserDeviceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDevice Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDevice)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddUserDeviceNoGCMCodeCompletedEventHandler(object sender, AddUserDeviceNoGCMCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserDeviceNoGCMCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserDeviceNoGCMCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDevice Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDevice)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteUserDeviceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ModifyUserDeviceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDeviceIdCompletedEventHandler(object sender, GetDeviceIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeviceIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeviceIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int GetDeviceIdResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GetDeviceIdResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendTestNotificationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MarkDeviceActiveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void MarkDeviceInactiveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591