#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ComputeAndroidApp.Resource", IsApplication=true)]

namespace ComputeAndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int btnDeregisterDevice = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int btnLogin = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btnRegister = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int btnSubmitRegistration = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int lblLogin = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int listView1 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int tableRow1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int tableRow2 = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int tableRow3 = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int txtDeviceId = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int txtForename = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int txtPassword = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int txtSurname = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int txtUsername = 2131034115;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Overview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Register = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
